#!/usr/bin/env python3
"""Generate the counter type ID constants from Aeron's AeronCounters.h.

Writes src/counter_types.rs (the `counter_types` module) and
src/counter_types.h (static_asserts checking each value against the header the
shim is compiled with). The output is checked in; rerun this script after an
Aeron upgrade:

    python3 scripts/gen_counter_types.py [path/to/AeronCounters.h]

Without an argument the header is taken from the most recent cargo build.
"""

import glob
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

TOKEN = re.compile(
    r"/\*\*(?P<doc>.*?)\*/"
    r"|//\s*(?P<section>[^\n]*)"
    r"|const\s+std::int32_t\s+(?P<name>\w+)\s*=\s*(?P<value>-?\d+)\s*;",
    re.S,
)


def find_header():
    if len(sys.argv) > 1:
        return Path(sys.argv[1])
    candidates = glob.glob(
        str(ROOT / "target/*/build/aeron-glide-*/out/aeron-*/aeron-client/src/main/cpp_wrapper/AeronCounters.h")
    )
    if not candidates:
        sys.exit("AeronCounters.h not found: run `cargo build` first or pass its path")
    return Path(max(candidates, key=os.path.getmtime))


def rustdoc(javadoc):
    """Javadoc comment body -> rustdoc lines."""
    lines = [re.sub(r"^\s*\*\s?", "", line).rstrip() for line in javadoc.strip().splitlines()]
    text = "\n".join(lines).strip()
    text = re.sub(r"\s*<p>\s*", "\n\n", text)
    text = re.sub(r"<b>(.*?)</b>", r"**\1**", text)
    text = re.sub(r"\{@link\s+([^}#]+)#([^}]+)\}", r"`\1::\2`", text)
    text = re.sub(r"\{@link\s+([^}]+)\}", r"`\1`", text)
    return [f"/// {line}".rstrip() for line in text.splitlines()]


def generate(header):
    text = header.read_text()
    start = text.index("namespace AeronCounters")
    body = text[start:text.index("\n}", start)]  # up to the namespace's closing brace
    rust, asserts = [], []
    doc = None
    for m in TOKEN.finditer(body):
        if m.group("doc") is not None:
            doc = m.group("doc")
        elif m.group("section") is not None:
            section = m.group("section").strip()
            rust.append(f"\n// {section}\n")
            doc = None
        else:
            name, value = m.group("name"), m.group("value")
            lines = rustdoc(doc) if doc else []
            rust.append("\n".join(lines + [f"pub const {name}: i32 = {value};"]) + "\n")
            asserts.append(f'static_assert(aeron::AeronCounters::{name} == {value}, "rerun scripts/gen_counter_types.py");')
            doc = None
    return rust, asserts


def main():
    header = find_header()
    src = "AeronCounters.h (" + header.parts[header.parts.index("out") + 1] + ")" if "out" in header.parts else header.name
    rust, asserts = generate(header)
    (ROOT / "src/counter_types.rs").write_text(
        f"// @generated by scripts/gen_counter_types.py from {src}. Do not edit.\n"
        "//! Type IDs of the counters allocated by the media driver, the archive and\n"
        "//! the cluster (C++ `aeron::AeronCounters`), as reported by\n"
        "//! [`CountersReader::get_counter_type_id`](crate::CountersReader::get_counter_type_id).\n"
        "//!\n"
        "//! Use other IDs for your own counters ([`AeronClient::add_counter`](crate::AeronClient::add_counter)).\n\n"
        + "\n".join(rust)
    )
    (ROOT / "src/counter_types.h").write_text(
        f"// @generated by scripts/gen_counter_types.py from {src}. Do not edit.\n"
        "// Checks src/counter_types.rs against the header the shim is compiled with.\n"
        "#pragma once\n#include <AeronCounters.h>\n\n" + "\n".join(asserts) + "\n"
    )
    subprocess.run(["rustfmt", "--edition", "2024", str(ROOT / "src/counter_types.rs")], check=True)
    print(f"{len(asserts)} counter type ids", file=sys.stderr)


if __name__ == "__main__":
    main()
