// @generated by scripts/gen_counter_types.py from AeronCounters.h (aeron-1.53.3). Do not edit.
//! Type IDs of the counters allocated by the media driver, the archive and
//! the cluster (C++ `aeron::AeronCounters`), as reported by
//! [`CountersReader::get_counter_type_id`](crate::CountersReader::get_counter_type_id).
//!
//! Use other IDs for your own counters ([`AeronClient::add_counter`](crate::AeronClient::add_counter)).

/// System-wide counters for monitoring. These are separate from counters used for position tracking on streams.
pub const DRIVER_SYSTEM_COUNTER_TYPE_ID: i32 = 0;

/// The limit as a position in bytes applied to publishers on a session-channel-stream tuple. Publishers will
/// experience back pressure when this position is passed as a means of flow control.
pub const DRIVER_PUBLISHER_LIMIT_TYPE_ID: i32 = 1;

/// The position the Sender has reached for sending data to the media on a session-channel-stream tuple.
pub const DRIVER_SENDER_POSITION_TYPE_ID: i32 = 2;

/// The highest position the Receiver has observed on a session-channel-stream tuple while rebuilding the stream.
/// It is possible the stream is not complete to this point if the stream has experienced loss.
pub const DRIVER_RECEIVER_HWM_TYPE_ID: i32 = 3;

/// The position an individual Subscriber has reached on a session-channel-stream tuple. It is possible to have
/// multiple
pub const DRIVER_SUBSCRIBER_POSITION_TYPE_ID: i32 = 4;

/// The highest position the Receiver has rebuilt up to on a session-channel-stream tuple while rebuilding the
/// stream.
/// The stream is complete up to this point.
pub const DRIVER_RECEIVER_POS_TYPE_ID: i32 = 5;

/// The status of a send-channel-endpoint represented as a counter value.
pub const DRIVER_SEND_CHANNEL_STATUS_TYPE_ID: i32 = 6;

/// The status of a receive-channel-endpoint represented as a counter value.
pub const DRIVER_RECEIVE_CHANNEL_STATUS_TYPE_ID: i32 = 7;

/// The position the Sender can immediately send up-to on a session-channel-stream tuple.
pub const DRIVER_SENDER_LIMIT_TYPE_ID: i32 = 9;

/// A counter per Image indicating presence of the congestion control.
pub const DRIVER_PER_IMAGE_TYPE_ID: i32 = 10;

/// A counter for tracking the last heartbeat of an entity with a given registration id.
pub const DRIVER_HEARTBEAT_TYPE_ID: i32 = 11;

/// The position in bytes a publication has reached appending to the log.
///
/// **Note:** This is a not a real-time value like the other and is updated one per second for monitoring
/// purposes.
pub const DRIVER_PUBLISHER_POS_TYPE_ID: i32 = 12;

/// Count of back-pressure events (BPE)s a sender has experienced on a stream.
pub const DRIVER_SENDER_BPE_TYPE_ID: i32 = 13;

/// Count of media driver neighbors for name resolution.
pub const NAME_RESOLVER_NEIGHBORS_COUNTER_TYPE_ID: i32 = 15;

/// Count of entries in the name resolver cache.
pub const NAME_RESOLVER_CACHE_ENTRIES_COUNTER_TYPE_ID: i32 = 16;

/// Counter used to store the status of a bind address and port for the local end of a channel.
///
/// When the value is `ChannelEndpointStatus::ACTIVE` then the key value and label will be updated with the
/// socket address and port which is bound.
pub const DRIVER_LOCAL_SOCKET_ADDRESS_STATUS_TYPE_ID: i32 = 14;

/// Count of number of active receivers for flow control strategy.
pub const FLOW_CONTROL_RECEIVERS_COUNTER_TYPE_ID: i32 = 17;

/// Count of number of destinations for multi-destination cast channels.
pub const MDC_DESTINATIONS_COUNTER_TYPE_ID: i32 = 18;

/// Counter for each bootstrap neighbors used for driver name resolution.
pub const NAME_RESOLVER_BOOTSTRAP_NEIGHBOR_COUNTER_TYPE_ID: i32 = 21;

// Archive counters

/// The position a recording has reached when being archived.
pub const ARCHIVE_RECORDING_POSITION_TYPE_ID: i32 = 100;

/// The type id of the `Counter` used for keeping track of the number of errors that have occurred.
pub const ARCHIVE_ERROR_COUNT_TYPE_ID: i32 = 101;

/// The type id of the `Counter` used for keeping track of the count of concurrent control sessions.
pub const ARCHIVE_CONTROL_SESSIONS_TYPE_ID: i32 = 102;

/// The type id of the `Counter` used for keeping track of the max duty cycle time of an archive agent.
pub const ARCHIVE_MAX_CYCLE_TIME_TYPE_ID: i32 = 103;

/// The type id of the `Counter` used for keeping track of the count of cycle time threshold exceeded of
/// an archive agent.
pub const ARCHIVE_CYCLE_TIME_THRESHOLD_EXCEEDED_TYPE_ID: i32 = 104;

/// The type id of the `Counter` used for keeping track of the max time it took recoder to write a block of
/// data to the storage.
pub const ARCHIVE_RECORDER_MAX_WRITE_TIME_TYPE_ID: i32 = 105;

/// The type id of the `Counter` used for keeping track of the total number of bytes written by the recorder
/// to the storage.
pub const ARCHIVE_RECORDER_TOTAL_WRITE_BYTES_TYPE_ID: i32 = 106;

/// The type id of the `Counter` used for keeping track of the total time the recorder spent writing data to
/// the storage.
pub const ARCHIVE_RECORDER_TOTAL_WRITE_TIME_TYPE_ID: i32 = 107;

/// The type id of the `Counter` used for keeping track of the max time it took replayer to read a block from
/// the storage.
pub const ARCHIVE_REPLAYER_MAX_READ_TIME_TYPE_ID: i32 = 108;

/// The type id of the `Counter` used for keeping track of the total number of bytes read by the replayer from
/// the storage.
pub const ARCHIVE_REPLAYER_TOTAL_READ_BYTES_TYPE_ID: i32 = 109;

/// The type id of the `Counter` used for keeping track of the total time the replayer spent reading data from
/// the storage.
pub const ARCHIVE_REPLAYER_TOTAL_READ_TIME_TYPE_ID: i32 = 110;

/// The type id of the `Counter` used for tracking the count of active recording sessions.
pub const ARCHIVE_RECORDING_SESSION_COUNT_TYPE_ID: i32 = 111;

/// The type id of the `Counter` used for tracking the count of active replay sessions.
pub const ARCHIVE_REPLAY_SESSION_COUNT_TYPE_ID: i32 = 112;

// Cluster counters

/// Counter type id for the consensus module state.
pub const CLUSTER_CONSENSUS_MODULE_STATE_TYPE_ID: i32 = 200;

/// Counter type id for the cluster node role.
pub const CLUSTER_NODE_ROLE_TYPE_ID: i32 = 201;

/// Counter type id for the control toggle.
pub const CLUSTER_CONTROL_TOGGLE_TYPE_ID: i32 = 202;

/// Counter type id of the commit position.
pub const CLUSTER_COMMIT_POSITION_TYPE_ID: i32 = 203;

/// Counter representing the Recovery State for the cluster.
pub const CLUSTER_RECOVERY_STATE_TYPE_ID: i32 = 204;

/// Counter type id for count of snapshots taken.
pub const CLUSTER_SNAPSHOT_COUNTER_TYPE_ID: i32 = 205;

/// Counter type for count of standby snapshots received.
pub const CLUSTER_STANDBY_SNAPSHOT_COUNTER_TYPE_ID: i32 = 232;

/// Type id for election state counter.
pub const CLUSTER_ELECTION_STATE_TYPE_ID: i32 = 207;

/// The type id of the `Counter` used for the backup state.
pub const CLUSTER_BACKUP_STATE_TYPE_ID: i32 = 208;

/// The type id of the `Counter` used for the live log position counter.
pub const CLUSTER_BACKUP_LIVE_LOG_POSITION_TYPE_ID: i32 = 209;

/// The type id of the `Counter` used for the next query deadline counter.
pub const CLUSTER_BACKUP_QUERY_DEADLINE_TYPE_ID: i32 = 210;

/// The type id of the `Counter` used for keeping track of the number of errors that have occurred.
pub const CLUSTER_BACKUP_ERROR_COUNT_TYPE_ID: i32 = 211;

/// Counter type id for the consensus module error count.
pub const CLUSTER_CONSENSUS_MODULE_ERROR_COUNT_TYPE_ID: i32 = 212;

/// Counter type id for the number of cluster clients which have been timed out.
pub const CLUSTER_CLIENT_TIMEOUT_COUNT_TYPE_ID: i32 = 213;

/// Counter type id for the number of invalid requests which the cluster has received.
pub const CLUSTER_INVALID_REQUEST_COUNT_TYPE_ID: i32 = 214;

/// Counter type id for the clustered service error count.
pub const CLUSTER_CLUSTERED_SERVICE_ERROR_COUNT_TYPE_ID: i32 = 215;

/// The type id of the `Counter` used for keeping track of the max duty cycle time of the consensus module.
pub const CLUSTER_MAX_CYCLE_TIME_TYPE_ID: i32 = 216;

/// The type id of the `Counter` used for keeping track of the count of cycle time threshold exceeded of
/// the consensus module.
pub const CLUSTER_CYCLE_TIME_THRESHOLD_EXCEEDED_TYPE_ID: i32 = 217;

/// The type id of the `Counter` used for keeping track of the max duty cycle time of the service container.
pub const CLUSTER_CLUSTERED_SERVICE_MAX_CYCLE_TIME_TYPE_ID: i32 = 218;

/// The type id of the `Counter` used for keeping track of the count of cycle time threshold exceeded of
/// the service container.
pub const CLUSTER_CLUSTERED_SERVICE_CYCLE_TIME_THRESHOLD_EXCEEDED_TYPE_ID: i32 = 219;

/// The type id of the `Counter` used for the cluster standby state.
pub const CLUSTER_STANDBY_STATE_TYPE_ID: i32 = 220;

/// Counter type id for the clustered service error count.
pub const CLUSTER_STANDBY_ERROR_COUNT_TYPE_ID: i32 = 221;

/// Counter type for responses to heartbeat request from the cluster.
pub const CLUSTER_STANDBY_HEARTBEAT_RESPONSE_COUNT_TYPE_ID: i32 = 222;

/// Standby control toggle type id
pub const CLUSTER_STANDBY_CONTROL_TOGGLE_TYPE_ID: i32 = 223;

/// The type id of the `Counter` used for keeping track of the max duty cycle time of the cluster standby.
pub const CLUSTER_STANDBY_MAX_CYCLE_TIME_TYPE_ID: i32 = 227;

/// The type id of the `Counter` used for keeping track of the count of cycle time threshold exceeded of
/// the cluster standby.
pub const CLUSTER_STANDBY_CYCLE_TIME_THRESHOLD_EXCEEDED_TYPE_ID: i32 = 228;

/// The type id of the `Counter` to make visible the memberId that the cluster standby is currently using to
/// as a source for the cluster log.
pub const CLUSTER_STANDBY_SOURCE_MEMBER_ID_TYPE_ID: i32 = 231;

/// Counter type id for the transition module error count.
pub const TRANSITION_MODULE_ERROR_COUNT_TYPE_ID: i32 = 226;

/// The type if of the `Counter` used for transition module state
pub const TRANSITION_MODULE_STATE_TYPE_ID: i32 = 224;

/// The type id of the `Counter` used for keeping track of the max duty cycle time of the transition module.
pub const TRANSITION_MODULE_MAX_CYCLE_TIME_TYPE_ID: i32 = 229;

/// The type id of the `Counter` used for keeping track of the count of cycle time threshold exceeded of
/// the transition module.
pub const TRANSITION_MODULE_CYCLE_TIME_THRESHOLD_EXCEEDED_TYPE_ID: i32 = 230;

/// The type of the `Counter` used for handling node specific operations.
pub const NODE_CONTROL_TOGGLE_TYPE_ID: i32 = 233;

/// The type id of the `Counter` used for keeping track of the maximum total snapshot duration.
pub const CLUSTER_TOTAL_MAX_SNAPSHOT_DURATION_TYPE_ID: i32 = 234;

/// The type id of the `Counter` used for keeping track of the count total snapshot duration
/// has exceeded the threshold.
pub const CLUSTER_TOTAL_SNAPSHOT_DURATION_THRESHOLD_EXCEEDED_TYPE_ID: i32 = 235;

/// The type id of the `Counter` used for keeping track of the maximum snapshot duration
/// for a given clustered service.
pub const CLUSTERED_SERVICE_MAX_SNAPSHOT_DURATION_TYPE_ID: i32 = 236;

/// The type id of the `Counter` used for keeping track of the count snapshot duration
/// has exceeded the threshold for a given clustered service.
pub const CLUSTERED_SERVICE_SNAPSHOT_DURATION_THRESHOLD_EXCEEDED_TYPE_ID: i32 = 237;

/// The type id of the `Counter` used for keeping track of the number of elections that have occurred.
pub const CLUSTER_ELECTION_COUNT_TYPE_ID: i32 = 238;

/// The type id of the `Counter` used for keeping track of the Cluster leadership term id.
pub const CLUSTER_LEADERSHIP_TERM_ID_TYPE_ID: i32 = 239;
