// @generated by scripts/gen_driver_context.py from aeron-driver/src/main/c/aeronmd.h (aeron-1.53.3). Do not edit.
//! Media driver settings (`aeron_driver_context_set_*` / `get_*`).
//!
//! Not generated (function pointers or driver-internal structs):
//! - `aeron_driver_context_set_multicast_flowcontrol_supplier(aeron_flow_control_strategy_supplier_func_t)`
//! - `aeron_driver_context_set_unicast_flowcontrol_supplier(aeron_flow_control_strategy_supplier_func_t)`
//! - `aeron_driver_context_set_congestioncontrol_supplier(aeron_congestion_control_strategy_supplier_func_t)`
//! - `aeron_driver_context_set_agent_on_start_function(aeron_agent_on_start_func_t, void *)`
//! - `aeron_driver_context_set_driver_termination_validator(aeron_driver_termination_validator_func_t, void *)`
//! - `aeron_driver_context_set_driver_termination_hook(aeron_driver_termination_hook_func_t, void *)`
//! - `aeron_driver_context_set_udp_channel_transport_bindings(aeron_udp_channel_transport_bindings_t *)`
//! - `aeron_driver_context_set_udp_channel_outgoing_interceptors(aeron_udp_channel_interceptor_bindings_t *)`
//! - `aeron_driver_context_set_udp_channel_incoming_interceptors(aeron_udp_channel_interceptor_bindings_t *)`
//! - `aeron_driver_context_set_name_resolver_supplier(aeron_name_resolver_supplier_func_t)`
//! - `aeron_driver_context_set_conductor_duty_cycle_tracker(aeron_duty_cycle_tracker_t *)`
//! - `aeron_driver_context_set_sender_duty_cycle_tracker(aeron_duty_cycle_tracker_t *)`
//! - `aeron_driver_context_set_receiver_duty_cycle_tracker(aeron_duty_cycle_tracker_t *)`
//! - `aeron_driver_context_set_name_resolver_time_tracker(aeron_duty_cycle_tracker_t *)`
//! - `aeron_driver_context_set_sender_port_manager(aeron_port_manager_t *)`
//! - `aeron_driver_context_set_receiver_port_manager(aeron_port_manager_t *)`
//! - `aeron_driver_context_get_agent_on_start_function -> aeron_agent_on_start_func_t`
//! - `aeron_driver_context_get_agent_on_start_state -> void *`
//! - `aeron_driver_context_get_conductor_duty_cycle_tracker -> aeron_duty_cycle_tracker_t *`
//! - `aeron_driver_context_get_congestioncontrol_supplier -> aeron_congestion_control_strategy_supplier_func_t`
//! - `aeron_driver_context_get_driver_termination_hook -> aeron_driver_termination_hook_func_t`
//! - `aeron_driver_context_get_driver_termination_hook_state -> void *`
//! - `aeron_driver_context_get_driver_termination_validator -> aeron_driver_termination_validator_func_t`
//! - `aeron_driver_context_get_driver_termination_validator_state -> void *`
//! - `aeron_driver_context_get_multicast_flowcontrol_supplier -> aeron_flow_control_strategy_supplier_func_t`
//! - `aeron_driver_context_get_name_resolver_supplier -> aeron_name_resolver_supplier_func_t`
//! - `aeron_driver_context_get_name_resolver_time_tracker -> aeron_duty_cycle_tracker_t *`
//! - `aeron_driver_context_get_receiver_duty_cycle_tracker -> aeron_duty_cycle_tracker_t *`
//! - `aeron_driver_context_get_receiver_port_manager -> aeron_port_manager_t *`
//! - `aeron_driver_context_get_sender_duty_cycle_tracker -> aeron_duty_cycle_tracker_t *`
//! - `aeron_driver_context_get_sender_port_manager -> aeron_port_manager_t *`
//! - `aeron_driver_context_get_udp_channel_incoming_interceptors -> aeron_udp_channel_interceptor_bindings_t *`
//! - `aeron_driver_context_get_udp_channel_outgoing_interceptors -> aeron_udp_channel_interceptor_bindings_t *`
//! - `aeron_driver_context_get_udp_channel_transport_bindings -> aeron_udp_channel_transport_bindings_t *`
//! - `aeron_driver_context_get_unicast_flowcontrol_supplier -> aeron_flow_control_strategy_supplier_func_t`
#![allow(clippy::too_many_arguments)]

use crate::{IdleStrategy, MediaDriver, MediaDriverBuilder};

#[cxx::bridge(namespace = "aeron_rs")]
pub(crate) mod ffi {
    unsafe extern "C++" {
        include!("driver_gen.h");

        type MediaDriverWrapper = crate::ffi::MediaDriverWrapper;

        fn driver_set_dir(driver: Pin<&mut MediaDriverWrapper>, value: &str) -> Result<()>;
        fn driver_set_dir_warn_if_exists(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_thread_naming(driver: Pin<&mut MediaDriverWrapper>, value: i32)
        -> Result<()>;
        fn driver_set_dir_delete_on_start(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_dir_delete_on_shutdown(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_to_conductor_buffer_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_to_clients_buffer_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_counters_buffer_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_error_buffer_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_client_liveness_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_term_buffer_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_ipc_term_buffer_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_term_buffer_sparse_file(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_perform_storage_checks(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_low_file_store_warning_threshold(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_spies_simulate_connection(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_file_page_size(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_mtu_length(driver: Pin<&mut MediaDriverWrapper>, value: usize) -> Result<()>;
        fn driver_set_ipc_mtu_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_ipc_publication_term_window_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_publication_term_window_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_publication_linger_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_socket_so_rcvbuf(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_socket_so_sndbuf(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_socket_multicast_ttl(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u8,
        ) -> Result<()>;
        fn driver_set_send_to_status_poll_ratio(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_rcv_status_message_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_image_liveness_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_rcv_initial_window_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_loss_report_buffer_length(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_publication_unblock_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_publication_connection_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_timer_interval_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_sender_idle_strategy(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_conductor_idle_strategy(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_receiver_idle_strategy(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_sharednetwork_idle_strategy(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_shared_idle_strategy(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_sender_idle_strategy_init_args(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_conductor_idle_strategy_init_args(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_receiver_idle_strategy_init_args(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_sharednetwork_idle_strategy_init_args(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_shared_idle_strategy_init_args(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_native_resource_agent_idle_strategy(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_native_resource_agent_idle_strategy_init_args(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_counters_free_to_reuse_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_flow_control_receiver_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_flow_control_group_tag(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i64,
        ) -> Result<()>;
        fn driver_set_flow_control_group_min_size(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_receiver_group_tag(
            driver: Pin<&mut MediaDriverWrapper>,
            is_present: bool,
            value: i64,
        ) -> Result<()>;
        fn driver_set_print_configuration(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_reliable_stream(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_tether_subscriptions(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_untethered_window_limit_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_untethered_linger_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_untethered_resting_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_driver_timeout_ms(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_nak_multicast_group_size(
            driver: Pin<&mut MediaDriverWrapper>,
            value: usize,
        ) -> Result<()>;
        fn driver_set_nak_multicast_max_backoff_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_nak_unicast_delay_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_nak_unicast_retry_delay_ratio(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_max_resend(driver: Pin<&mut MediaDriverWrapper>, value: u32) -> Result<()>;
        fn driver_set_retransmit_unicast_delay_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_retransmit_unicast_linger_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_receiver_group_consideration(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_rejoin_stream(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_connect_enabled(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_publication_reserved_session_id_low(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_publication_reserved_session_id_high(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_resolver_name(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_resolver_interface(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_resolver_bootstrap_neighbor(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_name_resolver_init_args(
            driver: Pin<&mut MediaDriverWrapper>,
            value: &str,
        ) -> Result<()>;
        fn driver_set_resolver_neighbor_timeout_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_self_resolution_interval_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_resolver_neighbor_resolution_interval_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_resolver_bootstrap_neighbor_resolution_interval_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_re_resolution_check_interval_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_sender_wildcard_port_range(
            driver: Pin<&mut MediaDriverWrapper>,
            low: u16,
            high: u16,
        ) -> Result<()>;
        fn driver_set_receiver_wildcard_port_range(
            driver: Pin<&mut MediaDriverWrapper>,
            low: u16,
            high: u16,
        ) -> Result<()>;
        fn driver_set_conductor_cycle_threshold_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_sender_cycle_threshold_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_receiver_cycle_threshold_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_name_resolver_threshold_ns(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u64,
        ) -> Result<()>;
        fn driver_set_receiver_io_vector_capacity(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u32,
        ) -> Result<()>;
        fn driver_set_sender_io_vector_capacity(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u32,
        ) -> Result<()>;
        fn driver_set_network_publication_max_messages_per_send(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u32,
        ) -> Result<()>;
        fn driver_set_resource_free_limit(
            driver: Pin<&mut MediaDriverWrapper>,
            value: u32,
        ) -> Result<()>;
        fn driver_set_conductor_cpu_affinity(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_receiver_cpu_affinity(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_sender_cpu_affinity(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_native_resource_agent_cpu_affinity(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_set_cpuset_affinity(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_cpuset_warnings_as_errors(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_enable_experimental_features(
            driver: Pin<&mut MediaDriverWrapper>,
            value: bool,
        ) -> Result<()>;
        fn driver_set_stream_session_limit(
            driver: Pin<&mut MediaDriverWrapper>,
            value: i32,
        ) -> Result<()>;
        fn driver_get_client_liveness_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_conductor_cpu_affinity(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_conductor_cycle_threshold_ns(driver: &MediaDriverWrapper) -> i64;
        fn driver_get_conductor_idle_strategy(driver: &MediaDriverWrapper) -> String;
        fn driver_get_conductor_idle_strategy_init_args(driver: &MediaDriverWrapper) -> String;
        fn driver_get_connect_enabled(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_counters_buffer_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_counters_free_to_reuse_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_cpuset_affinity(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_cpuset_warnings_as_errors(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_dir(driver: &MediaDriverWrapper) -> String;
        fn driver_get_dir_delete_on_shutdown(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_dir_delete_on_start(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_dir_warn_if_exists(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_driver_timeout_ms(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_enable_experimental_features(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_error_buffer_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_file_page_size(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_flow_control_group_min_size(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_flow_control_group_tag(driver: &MediaDriverWrapper) -> i64;
        fn driver_get_flow_control_receiver_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_image_liveness_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_ipc_mtu_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_ipc_publication_term_window_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_ipc_term_buffer_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_loss_report_buffer_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_low_file_store_warning_threshold(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_max_resend(driver: &MediaDriverWrapper) -> u32;
        fn driver_get_mtu_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_nak_multicast_group_size(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_nak_multicast_max_backoff_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_nak_unicast_delay_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_nak_unicast_retry_delay_ratio(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_name_resolver_init_args(driver: &MediaDriverWrapper) -> String;
        fn driver_get_name_resolver_threshold_ns(driver: &MediaDriverWrapper) -> i64;
        fn driver_get_native_resource_agent_cpu_affinity(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_native_resource_agent_idle_strategy(driver: &MediaDriverWrapper) -> String;
        fn driver_get_native_resource_agent_idle_strategy_init_args(
            driver: &MediaDriverWrapper,
        ) -> String;
        fn driver_get_network_publication_max_messages_per_send(driver: &MediaDriverWrapper)
        -> u32;
        fn driver_get_perform_storage_checks(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_print_configuration(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_publication_connection_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_publication_linger_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_publication_reserved_session_id_high(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_publication_reserved_session_id_low(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_publication_term_window_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_publication_unblock_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_rcv_initial_window_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_rcv_status_message_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_re_resolution_check_interval_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_receiver_cpu_affinity(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_receiver_cycle_threshold_ns(driver: &MediaDriverWrapper) -> i64;
        fn driver_get_receiver_group_consideration(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_receiver_group_tag_is_present(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_receiver_group_tag_value(driver: &MediaDriverWrapper) -> i64;
        fn driver_get_receiver_idle_strategy(driver: &MediaDriverWrapper) -> String;
        fn driver_get_receiver_idle_strategy_init_args(driver: &MediaDriverWrapper) -> String;
        fn driver_get_receiver_io_vector_capacity(driver: &MediaDriverWrapper) -> u32;
        fn driver_get_rejoin_stream(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_reliable_stream(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_resolver_bootstrap_neighbor(driver: &MediaDriverWrapper) -> String;
        fn driver_get_resolver_bootstrap_resolution_interval_ns(driver: &MediaDriverWrapper)
        -> u64;
        fn driver_get_resolver_interface(driver: &MediaDriverWrapper) -> String;
        fn driver_get_resolver_name(driver: &MediaDriverWrapper) -> String;
        fn driver_get_resolver_neighbor_resolution_interval_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_resolver_neighbor_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_resource_free_limit(driver: &MediaDriverWrapper) -> u32;
        fn driver_get_retransmit_unicast_delay_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_retransmit_unicast_linger_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_self_resolution_interval_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_send_to_status_poll_ratio(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_sender_cpu_affinity(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_sender_cycle_threshold_ns(driver: &MediaDriverWrapper) -> i64;
        fn driver_get_sender_idle_strategy(driver: &MediaDriverWrapper) -> String;
        fn driver_get_sender_idle_strategy_init_args(driver: &MediaDriverWrapper) -> String;
        fn driver_get_sender_io_vector_capacity(driver: &MediaDriverWrapper) -> u32;
        fn driver_get_shared_idle_strategy(driver: &MediaDriverWrapper) -> String;
        fn driver_get_shared_idle_strategy_init_args(driver: &MediaDriverWrapper) -> String;
        fn driver_get_sharednetwork_idle_strategy(driver: &MediaDriverWrapper) -> String;
        fn driver_get_sharednetwork_idle_strategy_init_args(driver: &MediaDriverWrapper) -> String;
        fn driver_get_socket_multicast_ttl(driver: &MediaDriverWrapper) -> u8;
        fn driver_get_socket_so_rcvbuf(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_socket_so_sndbuf(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_spies_simulate_connection(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_stream_session_limit(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_term_buffer_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_term_buffer_sparse_file(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_tether_subscriptions(driver: &MediaDriverWrapper) -> bool;
        fn driver_get_thread_naming(driver: &MediaDriverWrapper) -> i32;
        fn driver_get_timer_interval_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_to_clients_buffer_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_to_conductor_buffer_length(driver: &MediaDriverWrapper) -> usize;
        fn driver_get_untethered_linger_timeout_ns(driver: &MediaDriverWrapper) -> i64;
        fn driver_get_untethered_resting_timeout_ns(driver: &MediaDriverWrapper) -> u64;
        fn driver_get_untethered_window_limit_timeout_ns(driver: &MediaDriverWrapper) -> u64;
    }
}

/// How the media driver names its threads (`aeron_thread_naming_t`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ThreadNaming {
    /// `AERON_THREAD_NAMING_CLASSIC`.
    Classic = 0,
    /// `AERON_THREAD_NAMING_NEW`.
    New = 1,
}

impl ThreadNaming {
    fn from_c(value: i32) -> Self {
        if value == 1 { Self::New } else { Self::Classic }
    }
}

/// A boolean setting that can be forced or inferred (`aeron_inferable_boolean_t`).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InferableBoolean {
    /// `AERON_FORCE_FALSE`.
    ForceFalse = 0,
    /// `AERON_FORCE_TRUE`.
    ForceTrue = 1,
    /// `AERON_INFER`.
    Infer = 2,
}

impl InferableBoolean {
    fn from_c(value: i32) -> Self {
        match value {
            0 => Self::ForceFalse,
            1 => Self::ForceTrue,
            _ => Self::Infer,
        }
    }
}

impl MediaDriverBuilder {
    /// The top level Aeron directory used for communication between a Media Driver and client.
    ///
    /// C: `aeron_driver_context_set_dir`, environment variable `AERON_DIR`.
    pub fn dir(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_dir(w, value))
    }

    /// Warn if the top level Aeron directory exists when starting the driver.
    ///
    /// C: `aeron_driver_context_set_dir_warn_if_exists`, environment variable `AERON_DIR_WARN_IF_EXISTS`.
    pub fn dir_warn_if_exists(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_dir_warn_if_exists(w, value))
    }

    /// Sets `thread_naming`.
    ///
    /// C: `aeron_driver_context_set_thread_naming`, environment variable `AERON_THREAD_NAMING`.
    pub fn thread_naming(self, value: ThreadNaming) -> Self {
        self.apply(|w| ffi::driver_set_thread_naming(w, value as i32))
    }

    /// Attempt to delete directories on start if they exist.
    ///
    /// C: `aeron_driver_context_set_dir_delete_on_start`, environment variable `AERON_DIR_DELETE_ON_START`.
    pub fn dir_delete_on_start(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_dir_delete_on_start(w, value))
    }

    /// Attempt to delete directories on shutdown.
    ///
    /// C: `aeron_driver_context_set_dir_delete_on_shutdown`, environment variable `AERON_DIR_DELETE_ON_SHUTDOWN`.
    pub fn dir_delete_on_shutdown(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_dir_delete_on_shutdown(w, value))
    }

    /// Length (in bytes) of the conductor buffer for control commands from the clients to the media driver conductor.
    ///
    /// C: `aeron_driver_context_set_to_conductor_buffer_length`, environment variable `AERON_CONDUCTOR_BUFFER_LENGTH`.
    pub fn to_conductor_buffer_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_to_conductor_buffer_length(w, value))
    }

    /// Length (in bytes) of the broadcast buffers from the media driver to the clients.
    ///
    /// C: `aeron_driver_context_set_to_clients_buffer_length`, environment variable `AERON_CLIENTS_BUFFER_LENGTH`.
    pub fn to_clients_buffer_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_to_clients_buffer_length(w, value))
    }

    /// Length (in bytes) of the value buffer for the system counters.
    ///
    /// C: `aeron_driver_context_set_counters_buffer_length`, environment variable `AERON_COUNTERS_BUFFER_LENGTH`.
    pub fn counters_buffer_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_counters_buffer_length(w, value))
    }

    /// Length (in bytes) of the buffer for the distinct error log.
    ///
    /// C: `aeron_driver_context_set_error_buffer_length`, environment variable `AERON_ERROR_BUFFER_LENGTH`.
    pub fn error_buffer_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_error_buffer_length(w, value))
    }

    /// Client liveness timeout in nanoseconds
    ///
    /// C: `aeron_driver_context_set_client_liveness_timeout_ns`, environment variable `AERON_CLIENT_LIVENESS_TIMEOUT`.
    pub fn client_liveness_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_client_liveness_timeout_ns(w, value))
    }

    /// Length (in bytes) of the log buffers for publication terms.
    ///
    /// C: `aeron_driver_context_set_term_buffer_length`, environment variable `AERON_TERM_BUFFER_LENGTH`.
    pub fn term_buffer_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_term_buffer_length(w, value))
    }

    /// Length (in bytes) of the log buffers for IPC publication terms.
    ///
    /// C: `aeron_driver_context_set_ipc_term_buffer_length`, environment variable `AERON_IPC_TERM_BUFFER_LENGTH`.
    pub fn ipc_term_buffer_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_ipc_term_buffer_length(w, value))
    }

    /// Should term buffers be created sparse.
    ///
    /// C: `aeron_driver_context_set_term_buffer_sparse_file`, environment variable `AERON_TERM_BUFFER_SPARSE_FILE`.
    pub fn term_buffer_sparse_file(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_term_buffer_sparse_file(w, value))
    }

    /// Should storage checks should be performed when allocating files.
    ///
    /// C: `aeron_driver_context_set_perform_storage_checks`, environment variable `AERON_PERFORM_STORAGE_CHECKS`.
    pub fn perform_storage_checks(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_perform_storage_checks(w, value))
    }

    /// Specify the interval which checks for re-resolutions of names occurs.
    ///
    /// C: `aeron_driver_context_set_low_file_store_warning_threshold`, environment variable `AERON_LOW_FILE_STORE_WARNING_THRESHOLD`.
    pub fn low_file_store_warning_threshold(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_low_file_store_warning_threshold(w, value))
    }

    /// Should a spy subscription simulate a connection to a network publication.
    ///
    /// C: `aeron_driver_context_set_spies_simulate_connection`, environment variable `AERON_SPIES_SIMULATE_CONNECTION`.
    pub fn spies_simulate_connection(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_spies_simulate_connection(w, value))
    }

    /// Page size for alignment of all files.
    ///
    /// C: `aeron_driver_context_set_file_page_size`, environment variable `AERON_FILE_PAGE_SIZE`.
    pub fn file_page_size(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_file_page_size(w, value))
    }

    /// Length (in bytes) of the maximum transmission unit of the publication.
    ///
    /// C: `aeron_driver_context_set_mtu_length`, environment variable `AERON_MTU_LENGTH`.
    pub fn mtu_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_mtu_length(w, value))
    }

    /// Length (in bytes) of the maximum transmission unit of the IPC publication.
    ///
    /// C: `aeron_driver_context_set_ipc_mtu_length`, environment variable `AERON_IPC_MTU_LENGTH`.
    pub fn ipc_mtu_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_ipc_mtu_length(w, value))
    }

    /// Window limit on IPC Publication side.
    ///
    /// C: `aeron_driver_context_set_ipc_publication_term_window_length`, environment variable `AERON_IPC_PUBLICATION_TERM_WINDOW_LENGTH`.
    pub fn ipc_publication_term_window_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_ipc_publication_term_window_length(w, value))
    }

    /// Window limit on Publication side.
    ///
    /// C: `aeron_driver_context_set_publication_term_window_length`, environment variable `AERON_PUBLICATION_TERM_WINDOW_LENGTH`.
    pub fn publication_term_window_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_publication_term_window_length(w, value))
    }

    /// Linger timeout in nanoseconds on publications.
    ///
    /// C: `aeron_driver_context_set_publication_linger_timeout_ns`, environment variable `AERON_PUBLICATION_LINGER_TIMEOUT`.
    pub fn publication_linger_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_publication_linger_timeout_ns(w, value))
    }

    /// SO_RCVBUF setting on UDP sockets which must be sufficient for Bandwidth Delay Product (BDP).
    ///
    /// C: `aeron_driver_context_set_socket_so_rcvbuf`, environment variable `AERON_SOCKET_SO_RCVBUF`.
    pub fn socket_so_rcvbuf(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_socket_so_rcvbuf(w, value))
    }

    /// SO_SNDBUF setting on UDP sockets which must be sufficient for Bandwidth Delay Product (BDP).
    ///
    /// C: `aeron_driver_context_set_socket_so_sndbuf`, environment variable `AERON_SOCKET_SO_SNDBUF`.
    pub fn socket_so_sndbuf(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_socket_so_sndbuf(w, value))
    }

    /// IP_MULTICAST_TTL setting on outgoing UDP sockets.
    ///
    /// C: `aeron_driver_context_set_socket_multicast_ttl`, environment variable `AERON_SOCKET_MULTICAST_TTL`.
    pub fn socket_multicast_ttl(self, value: u8) -> Self {
        self.apply(|w| ffi::driver_set_socket_multicast_ttl(w, value))
    }

    /// Ratio of sending data to polling status messages in the Sender.
    ///
    /// C: `aeron_driver_context_set_send_to_status_poll_ratio`, environment variable `AERON_SEND_TO_STATUS_POLL_RATIO`.
    pub fn send_to_status_poll_ratio(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_send_to_status_poll_ratio(w, value))
    }

    /// Status Message timeout in nanoseconds.
    ///
    /// C: `aeron_driver_context_set_rcv_status_message_timeout_ns`, environment variable `AERON_RCV_STATUS_MESSAGE_TIMEOUT`.
    pub fn rcv_status_message_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_rcv_status_message_timeout_ns(w, value))
    }

    /// Image liveness timeout in nanoseconds
    ///
    /// C: `aeron_driver_context_set_image_liveness_timeout_ns`, environment variable `AERON_IMAGE_LIVENESS_TIMEOUT`.
    pub fn image_liveness_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_image_liveness_timeout_ns(w, value))
    }

    /// Length of the initial window which must be sufficient for Bandwidth Delay Product (BDP).
    ///
    /// C: `aeron_driver_context_set_rcv_initial_window_length`, environment variable `AERON_RCV_INITIAL_WINDOW_LENGTH`.
    pub fn rcv_initial_window_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_rcv_initial_window_length(w, value))
    }

    /// Length (in bytes) of the buffer for the loss report log.
    ///
    /// C: `aeron_driver_context_set_loss_report_buffer_length`, environment variable `AERON_LOSS_REPORT_BUFFER_LENGTH`.
    pub fn loss_report_buffer_length(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_loss_report_buffer_length(w, value))
    }

    /// Timeout for publication unblock in nanoseconds.
    ///
    /// C: `aeron_driver_context_set_publication_unblock_timeout_ns`, environment variable `AERON_PUBLICATION_UNBLOCK_TIMEOUT`.
    pub fn publication_unblock_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_publication_unblock_timeout_ns(w, value))
    }

    /// Timeout for publication connection in nanoseconds.
    ///
    /// C: `aeron_driver_context_set_publication_connection_timeout_ns`, environment variable `AERON_PUBLICATION_CONNECTION_TIMEOUT`.
    pub fn publication_connection_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_publication_connection_timeout_ns(w, value))
    }

    /// Interval (in nanoseconds) between checks for timers and timeouts.
    ///
    /// C: `aeron_driver_context_set_timer_interval_ns`, environment variable `AERON_TIMER_INTERVAL`.
    pub fn timer_interval_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_timer_interval_ns(w, value))
    }

    /// Idle strategy to be employed by Sender for DEDICATED Threading Mode.
    ///
    /// C: `aeron_driver_context_set_sender_idle_strategy`, environment variable `AERON_SENDER_IDLE_STRATEGY`.
    pub fn sender_idle_strategy(self, strategy: IdleStrategy) -> Self {
        self.apply(|w| ffi::driver_set_sender_idle_strategy(w, strategy.as_str()))
    }

    /// Idle strategy to be employed by Conductor for DEDICATED or SHARED_NETWORK Threading Mode.
    ///
    /// C: `aeron_driver_context_set_conductor_idle_strategy`, environment variable `AERON_CONDUCTOR_IDLE_STRATEGY`.
    pub fn conductor_idle_strategy(self, strategy: IdleStrategy) -> Self {
        self.apply(|w| ffi::driver_set_conductor_idle_strategy(w, strategy.as_str()))
    }

    /// Idle strategy to be employed by Receiver for DEDICATED Threading Mode.
    ///
    /// C: `aeron_driver_context_set_receiver_idle_strategy`, environment variable `AERON_RECEIVER_IDLE_STRATEGY`.
    pub fn receiver_idle_strategy(self, strategy: IdleStrategy) -> Self {
        self.apply(|w| ffi::driver_set_receiver_idle_strategy(w, strategy.as_str()))
    }

    /// Idle strategy to be employed by Sender and Receiver for SHARED_NETWORK Threading Mode.
    ///
    /// C: `aeron_driver_context_set_sharednetwork_idle_strategy`, environment variable `AERON_SHAREDNETWORK_IDLE_STRATEGY`.
    pub fn sharednetwork_idle_strategy(self, strategy: IdleStrategy) -> Self {
        self.apply(|w| ffi::driver_set_sharednetwork_idle_strategy(w, strategy.as_str()))
    }

    /// Idle strategy to be employed by Conductor, Sender, and Receiver for SHARED Threading Mode.
    ///
    /// C: `aeron_driver_context_set_shared_idle_strategy`, environment variable `AERON_SHARED_IDLE_STRATEGY`.
    pub fn shared_idle_strategy(self, strategy: IdleStrategy) -> Self {
        self.apply(|w| ffi::driver_set_shared_idle_strategy(w, strategy.as_str()))
    }

    /// Idle strategy init args to be employed by Sender for DEDICATED Threading Mode.
    ///
    /// C: `aeron_driver_context_set_sender_idle_strategy_init_args`, environment variable `AERON_SENDER_IDLE_STRATEGY_INIT_ARGS`.
    pub fn sender_idle_strategy_init_args(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_sender_idle_strategy_init_args(w, value))
    }

    /// Idle strategy init args to be employed by Conductor for DEDICATED or SHARED_NETWORK Threading Mode.
    ///
    /// C: `aeron_driver_context_set_conductor_idle_strategy_init_args`, environment variable `AERON_CONDUCTOR_IDLE_STRATEGY_INIT_ARGS`.
    pub fn conductor_idle_strategy_init_args(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_conductor_idle_strategy_init_args(w, value))
    }

    /// Idle strategy init args to be employed by Receiver for DEDICATED Threading Mode.
    ///
    /// C: `aeron_driver_context_set_receiver_idle_strategy_init_args`, environment variable `AERON_RECEIVER_IDLE_STRATEGY_INIT_ARGS`.
    pub fn receiver_idle_strategy_init_args(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_receiver_idle_strategy_init_args(w, value))
    }

    /// Idle strategy init args to be employed by Sender and Receiver for SHARED_NETWORK Threading Mode.
    ///
    /// C: `aeron_driver_context_set_sharednetwork_idle_strategy_init_args`, environment variable `AERON_SHAREDNETWORK_IDLE_STRATEGY_INIT_ARGS`.
    pub fn sharednetwork_idle_strategy_init_args(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_sharednetwork_idle_strategy_init_args(w, value))
    }

    /// Idle strategy init args to be employed by Conductor, Sender, and Receiver for SHARED Threading Mode.
    ///
    /// C: `aeron_driver_context_set_shared_idle_strategy_init_args`.
    pub fn shared_idle_strategy_init_args(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_shared_idle_strategy_init_args(w, value))
    }

    /// Idle strategy to be employed by AsyncExecutor when enabled.
    ///
    /// C: `aeron_driver_context_set_native_resource_agent_idle_strategy`, environment variable `AERON_DRIVER_NATIVE_RESOURCE_AGENT_IDLE_STRATEGY`.
    pub fn native_resource_agent_idle_strategy(self, strategy: IdleStrategy) -> Self {
        self.apply(|w| ffi::driver_set_native_resource_agent_idle_strategy(w, strategy.as_str()))
    }

    /// Idle strategy init args to be employed AsyncExecutor when enabled.
    ///
    /// C: `aeron_driver_context_set_native_resource_agent_idle_strategy_init_args`, environment variable `AERON_DRIVER_NATIVE_RESOURCE_AGENT_IDLE_STRATEGY_INIT_ARGS`.
    pub fn native_resource_agent_idle_strategy_init_args(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_native_resource_agent_idle_strategy_init_args(w, value))
    }

    /// Timeout for freed counters before they can be reused.
    ///
    /// C: `aeron_driver_context_set_counters_free_to_reuse_timeout_ns`, environment variable `AERON_COUNTERS_FREE_TO_REUSE_TIMEOUT`.
    pub fn counters_free_to_reuse_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_counters_free_to_reuse_timeout_ns(w, value))
    }

    /// Timeout for a receiver to be tracked.
    ///
    /// C: `aeron_driver_context_set_flow_control_receiver_timeout_ns`, environment variable `AERON_FLOW_CONTROL_RECEIVER_TIMEOUT`.
    pub fn flow_control_receiver_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_flow_control_receiver_timeout_ns(w, value))
    }

    /// Default receiver tag for publishers to group endpoints by using tagged flow control.
    ///
    /// C: `aeron_driver_context_set_flow_control_group_tag`, environment variable `AERON_FLOW_CONTROL_GROUP_TAG`.
    pub fn flow_control_group_tag(self, value: i64) -> Self {
        self.apply(|w| ffi::driver_set_flow_control_group_tag(w, value))
    }

    /// Default required group size to use in tagged multicast flow control.
    ///
    /// C: `aeron_driver_context_set_flow_control_group_min_size`, environment variable `AERON_FLOW_CONTROL_GROUP_MIN_SIZE`.
    pub fn flow_control_group_min_size(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_flow_control_group_min_size(w, value))
    }

    /// Default receiver tag to be sent on status messages from channel to handle tagged flow control.
    ///
    /// C: `aeron_driver_context_set_receiver_group_tag`, environment variable `AERON_RECEIVER_GROUP_TAG`.
    pub fn receiver_group_tag(self, tag: Option<i64>) -> Self {
        self.apply(|w| ffi::driver_set_receiver_group_tag(w, tag.is_some(), tag.unwrap_or(0)))
    }

    /// Should the driver print its configuration on start to stdout.
    ///
    /// C: `aeron_driver_context_set_print_configuration`, environment variable `AERON_PRINT_CONFIGURATION`.
    pub fn print_configuration(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_print_configuration(w, value))
    }

    /// Property name for default boolean value for if a stream is reliable. True to NAK, false to gap fill.
    ///
    /// C: `aeron_driver_context_set_reliable_stream`, environment variable `AERON_RELIABLE_STREAM`.
    pub fn reliable_stream(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_reliable_stream(w, value))
    }

    /// Property name for default boolean value for if subscriptions should have a tether for flow control.
    ///
    /// C: `aeron_driver_context_set_tether_subscriptions`, environment variable `AERON_TETHER_SUBSCRIPTIONS`.
    pub fn tether_subscriptions(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_tether_subscriptions(w, value))
    }

    /// Untethered subscriptions window limit timeout after which they are removed from flow control.
    ///
    /// C: `aeron_driver_context_set_untethered_window_limit_timeout_ns`, environment variable `AERON_UNTETHERED_WINDOW_LIMIT_TIMEOUT`.
    pub fn untethered_window_limit_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_untethered_window_limit_timeout_ns(w, value))
    }

    /// Timeout for an untethered subscriptions to stay in the linger state.
    ///
    /// C: `aeron_driver_context_set_untethered_linger_timeout_ns`, environment variable `AERON_UNTETHERED_LINGER_TIMEOUT`.
    pub fn untethered_linger_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_untethered_linger_timeout_ns(w, value))
    }

    /// Untethered subscriptions resting timeout before they are allowed to re join an active stream.
    ///
    /// C: `aeron_driver_context_set_untethered_resting_timeout_ns`, environment variable `AERON_UNTETHERED_RESTING_TIMEOUT`.
    pub fn untethered_resting_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_untethered_resting_timeout_ns(w, value))
    }

    /// Timeout in which the driver is expected to respond or heartbeat.
    ///
    /// C: `aeron_driver_context_set_driver_timeout_ms`, environment variable `AERON_DRIVER_TIMEOUT`.
    pub fn driver_timeout_ms(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_driver_timeout_ms(w, value))
    }

    /// Expected size of multicast receiver groups property name.
    ///
    /// C: `aeron_driver_context_set_nak_multicast_group_size`, environment variable `AERON_NAK_MULTICAST_GROUP_SIZE`.
    pub fn nak_multicast_group_size(self, value: usize) -> Self {
        self.apply(|w| ffi::driver_set_nak_multicast_group_size(w, value))
    }

    /// Max backoff time for multicast NAK delay randomisation in nanoseconds.
    ///
    /// C: `aeron_driver_context_set_nak_multicast_max_backoff_ns`, environment variable `AERON_NAK_MULTICAST_MAX_BACKOFF`.
    pub fn nak_multicast_max_backoff_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_nak_multicast_max_backoff_ns(w, value))
    }

    /// How long to delay before sending an initial NAK.
    ///
    /// C: `aeron_driver_context_set_nak_unicast_delay_ns`, environment variable `AERON_NAK_UNICAST_DELAY`.
    pub fn nak_unicast_delay_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_nak_unicast_delay_ns(w, value))
    }

    /// A ratio to apply to the nak unicast delay to calculate the resend delay. Used as a multipler.
    ///
    /// C: `aeron_driver_context_set_nak_unicast_retry_delay_ratio`, environment variable `AERON_NAK_UNICAST_RETRY_DELAY_RATIO`.
    pub fn nak_unicast_retry_delay_ratio(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_nak_unicast_retry_delay_ratio(w, value))
    }

    /// Max number of active retransmissions tracked for udp streams with group semantics.
    ///
    /// C: `aeron_driver_context_set_max_resend`, environment variable `AERON_MAX_RESEND`.
    pub fn max_resend(self, value: u32) -> Self {
        self.apply(|w| ffi::driver_set_max_resend(w, value))
    }

    /// How long to delay before sending a retransmit following a NAK.
    ///
    /// C: `aeron_driver_context_set_retransmit_unicast_delay_ns`, environment variable `AERON_RETRANSMIT_UNICAST_DELAY`.
    pub fn retransmit_unicast_delay_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_retransmit_unicast_delay_ns(w, value))
    }

    /// How long to linger after delay on a NAK.
    ///
    /// C: `aeron_driver_context_set_retransmit_unicast_linger_ns`, environment variable `AERON_RETRANSMIT_UNICAST_LINGER`.
    pub fn retransmit_unicast_linger_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_retransmit_unicast_linger_ns(w, value))
    }

    /// Group semantics for network subscriptions.
    ///
    /// C: `aeron_driver_context_set_receiver_group_consideration`, environment variable `AERON_RECEIVER_GROUP_CONSIDERATION`.
    pub fn receiver_group_consideration(self, value: InferableBoolean) -> Self {
        self.apply(|w| ffi::driver_set_receiver_group_consideration(w, value as i32))
    }

    /// Property name for default boolean value for if a stream is rejoinable. True to allow rejoin, false to not.
    ///
    /// C: `aeron_driver_context_set_rejoin_stream`, environment variable `AERON_REJOIN_STREAM`.
    pub fn rejoin_stream(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_rejoin_stream(w, value))
    }

    /// Sets `connect_enabled`.
    ///
    /// C: `aeron_driver_context_set_connect_enabled`, environment variable `AERON_DRIVER_CONNECT`.
    pub fn connect_enabled(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_connect_enabled(w, value))
    }

    /// Sets `publication_reserved_session_id_low`.
    ///
    /// C: `aeron_driver_context_set_publication_reserved_session_id_low`, environment variable `AERON_PUBLICATION_RESERVED_SESSION_ID_LOW`.
    pub fn publication_reserved_session_id_low(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_publication_reserved_session_id_low(w, value))
    }

    /// Sets `publication_reserved_session_id_high`.
    ///
    /// C: `aeron_driver_context_set_publication_reserved_session_id_high`, environment variable `AERON_PUBLICATION_RESERVED_SESSION_ID_HIGH`.
    pub fn publication_reserved_session_id_high(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_publication_reserved_session_id_high(w, value))
    }

    /// Set the name of the MediaDriver for name resolver purposes.
    ///
    /// C: `aeron_driver_context_set_resolver_name`, environment variable `AERON_DRIVER_RESOLVER_NAME`.
    pub fn resolver_name(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_resolver_name(w, value))
    }

    /// The interface of the MediaDriver for name resolver purposes.
    /// The format is hostname:port.
    ///
    /// C: `aeron_driver_context_set_resolver_interface`, environment variable `AERON_DRIVER_RESOLVER_INTERFACE`.
    pub fn resolver_interface(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_resolver_interface(w, value))
    }

    /// Get the bootstrap neighbor of the Media Driver for name resolver purposes.
    /// The format is comma separated list of hostname:port pairs and follows the URI format for the endpoint parameter.
    ///
    /// C: `aeron_driver_context_set_resolver_bootstrap_neighbor`, environment variable `AERON_DRIVER_RESOLVER_BOOTSTRAP_NEIGHBOR`.
    pub fn resolver_bootstrap_neighbor(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_resolver_bootstrap_neighbor(w, value))
    }

    /// Specify the name of the name resolver (supplier) to be used by this media driver
    ///
    /// C: `aeron_driver_context_set_name_resolver_init_args`, environment variable `AERON_NAME_RESOLVER_INIT_ARGS`.
    pub fn name_resolver_init_args(self, value: &str) -> Self {
        self.apply(|w| ffi::driver_set_name_resolver_init_args(w, value))
    }

    /// Property name for time to wait before removing a neighbor entry from the cache if an update for that neighbor has
    /// not been received.
    ///
    /// C: `aeron_driver_context_set_resolver_neighbor_timeout_ns`, environment variable `AERON_DRIVER_RESOLVER_NEIGHBOR_TIMEOUT`.
    pub fn resolver_neighbor_timeout_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_resolver_neighbor_timeout_ns(w, value))
    }

    /// Property name for the interval between sending name to address messages for this driver to its neighbors.
    ///
    /// C: `aeron_driver_context_set_self_resolution_interval_ns`, environment variable `AERON_DRIVER_RESOLVER_SELF_RESOLUTION_INTERVAL`.
    pub fn self_resolution_interval_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_self_resolution_interval_ns(w, value))
    }

    /// Property name for the interval between sending name to address messages for all known neighbors.
    ///
    /// C: `aeron_driver_context_set_resolver_neighbor_resolution_interval_ns`, environment variable `AERON_DRIVER_RESOLVER_NEIGHBOR_RESOLUTION_INTERVAL`.
    pub fn resolver_neighbor_resolution_interval_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_resolver_neighbor_resolution_interval_ns(w, value))
    }

    /// Sets `resolver_bootstrap_neighbor_resolution_interval_ns`.
    ///
    /// C: `aeron_driver_context_set_resolver_bootstrap_neighbor_resolution_interval_ns`, environment variable `AERON_DRIVER_RESOLVER_BOOTSTRAP_NEIGHBOR_RESOLUTION_INTERVAL`.
    pub fn resolver_bootstrap_neighbor_resolution_interval_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_resolver_bootstrap_neighbor_resolution_interval_ns(w, value))
    }

    /// Specify the interval which checks for re-resolutions of names occurs.
    ///
    /// C: `aeron_driver_context_set_re_resolution_check_interval_ns`, environment variable `AERON_DRIVER_RERESOLUTION_CHECK_INTERVAL`.
    pub fn re_resolution_check_interval_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_re_resolution_check_interval_ns(w, value))
    }

    /// Specify the sender wildcard port range.
    ///
    /// C: `aeron_driver_context_set_sender_wildcard_port_range`, environment variable `AERON_SENDER_WILDCARD_PORT_RANGE`.
    pub fn sender_wildcard_port_range(self, low: u16, high: u16) -> Self {
        self.apply(|w| ffi::driver_set_sender_wildcard_port_range(w, low, high))
    }

    /// Specify the receiver wildcard port range.
    ///
    /// C: `aeron_driver_context_set_receiver_wildcard_port_range`, environment variable `AERON_RECEIVER_WILDCARD_PORT_RANGE`.
    pub fn receiver_wildcard_port_range(self, low: u16, high: u16) -> Self {
        self.apply(|w| ffi::driver_set_receiver_wildcard_port_range(w, low, high))
    }

    /// Specify the duty cycle time threshold for the conductor.
    ///
    /// C: `aeron_driver_context_set_conductor_cycle_threshold_ns`, environment variable `AERON_DRIVER_CONDUCTOR_CYCLE_THRESHOLD`.
    pub fn conductor_cycle_threshold_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_conductor_cycle_threshold_ns(w, value))
    }

    /// Specify the duty cycle time threshold for the sender.
    ///
    /// C: `aeron_driver_context_set_sender_cycle_threshold_ns`, environment variable `AERON_DRIVER_SENDER_CYCLE_THRESHOLD`.
    pub fn sender_cycle_threshold_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_sender_cycle_threshold_ns(w, value))
    }

    /// Specify the duty cycle time threshold for the receiver.
    ///
    /// C: `aeron_driver_context_set_receiver_cycle_threshold_ns`, environment variable `AERON_DRIVER_RECEIVER_CYCLE_THRESHOLD`.
    pub fn receiver_cycle_threshold_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_receiver_cycle_threshold_ns(w, value))
    }

    /// Specify the duty cycle time threshold for the name_resolver.
    ///
    /// C: `aeron_driver_context_set_name_resolver_threshold_ns`, environment variable `AERON_DRIVER_NAME_RESOLVER_THRESHOLD`.
    pub fn name_resolver_threshold_ns(self, value: u64) -> Self {
        self.apply(|w| ffi::driver_set_name_resolver_threshold_ns(w, value))
    }

    /// Sets `receiver_io_vector_capacity`.
    ///
    /// C: `aeron_driver_context_set_receiver_io_vector_capacity`, environment variable `AERON_RECEIVER_IO_VECTOR_CAPACITY`.
    pub fn receiver_io_vector_capacity(self, value: u32) -> Self {
        self.apply(|w| ffi::driver_set_receiver_io_vector_capacity(w, value))
    }

    /// Sets `sender_io_vector_capacity`.
    ///
    /// C: `aeron_driver_context_set_sender_io_vector_capacity`, environment variable `AERON_SENDER_IO_VECTOR_CAPACITY`.
    pub fn sender_io_vector_capacity(self, value: u32) -> Self {
        self.apply(|w| ffi::driver_set_sender_io_vector_capacity(w, value))
    }

    /// Sets `network_publication_max_messages_per_send`.
    ///
    /// C: `aeron_driver_context_set_network_publication_max_messages_per_send`, environment variable `AERON_NETWORK_PUBLICATION_MAX_MESSAGES_PER_SEND`.
    pub fn network_publication_max_messages_per_send(self, value: u32) -> Self {
        self.apply(|w| ffi::driver_set_network_publication_max_messages_per_send(w, value))
    }

    /// Sets `resource_free_limit`.
    ///
    /// C: `aeron_driver_context_set_resource_free_limit`, environment variable `AERON_DRIVER_RESOURCE_FREE_LIMIT`.
    pub fn resource_free_limit(self, value: u32) -> Self {
        self.apply(|w| ffi::driver_set_resource_free_limit(w, value))
    }

    /// Sets `conductor_cpu_affinity`.
    ///
    /// C: `aeron_driver_context_set_conductor_cpu_affinity`, environment variable `AERON_CONDUCTOR_CPU_AFFINITY`.
    pub fn conductor_cpu_affinity(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_conductor_cpu_affinity(w, value))
    }

    /// Sets `receiver_cpu_affinity`.
    ///
    /// C: `aeron_driver_context_set_receiver_cpu_affinity`, environment variable `AERON_RECEIVER_CPU_AFFINITY`.
    pub fn receiver_cpu_affinity(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_receiver_cpu_affinity(w, value))
    }

    /// Sets `sender_cpu_affinity`.
    ///
    /// C: `aeron_driver_context_set_sender_cpu_affinity`, environment variable `AERON_SENDER_CPU_AFFINITY`.
    pub fn sender_cpu_affinity(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_sender_cpu_affinity(w, value))
    }

    /// Sets `native_resource_agent_cpu_affinity`.
    ///
    /// C: `aeron_driver_context_set_native_resource_agent_cpu_affinity`, environment variable `AERON_DRIVER_NATIVE_RESOURCE_AGENT_CPU_AFFINITY`.
    pub fn native_resource_agent_cpu_affinity(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_native_resource_agent_cpu_affinity(w, value))
    }

    /// Sets `cpuset_affinity`.
    ///
    /// C: `aeron_driver_context_set_cpuset_affinity`, environment variable `AERON_DRIVER_CPUSET_AFFINITY`.
    pub fn cpuset_affinity(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_cpuset_affinity(w, value))
    }

    /// Sets `cpuset_warnings_as_errors`.
    ///
    /// C: `aeron_driver_context_set_cpuset_warnings_as_errors`, environment variable `AERON_DRIVER_CPUSET_WARNINGS_AS_ERRORS`.
    pub fn cpuset_warnings_as_errors(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_cpuset_warnings_as_errors(w, value))
    }

    /// Set the list of filenames to dynamic libraries to load upon context init.
    ///
    /// C: `aeron_driver_context_set_enable_experimental_features`, environment variable `AERON_ENABLE_EXPERIMENTAL_FEATURES`.
    pub fn enable_experimental_features(self, value: bool) -> Self {
        self.apply(|w| ffi::driver_set_enable_experimental_features(w, value))
    }

    /// Limit the number of sessions for a given stream that the driver will support
    ///
    /// C: `aeron_driver_context_set_stream_session_limit`, environment variable `AERON_DRIVER_STREAM_SESSION_LIMIT`.
    pub fn stream_session_limit(self, value: i32) -> Self {
        self.apply(|w| ffi::driver_set_stream_session_limit(w, value))
    }
}

impl MediaDriver {
    /// The driver's `client_liveness_timeout_ns` setting (`aeron_driver_context_get_client_liveness_timeout_ns`).
    pub fn client_liveness_timeout_ns(&self) -> u64 {
        ffi::driver_get_client_liveness_timeout_ns(&self.inner)
    }

    /// The driver's `conductor_cpu_affinity` setting (`aeron_driver_context_get_conductor_cpu_affinity`).
    pub fn conductor_cpu_affinity(&self) -> i32 {
        ffi::driver_get_conductor_cpu_affinity(&self.inner)
    }

    /// The driver's `conductor_cycle_threshold_ns` setting (`aeron_driver_context_get_conductor_cycle_threshold_ns`).
    pub fn conductor_cycle_threshold_ns(&self) -> i64 {
        ffi::driver_get_conductor_cycle_threshold_ns(&self.inner)
    }

    /// The driver's `conductor_idle_strategy` setting (`aeron_driver_context_get_conductor_idle_strategy`).
    pub fn conductor_idle_strategy(&self) -> String {
        ffi::driver_get_conductor_idle_strategy(&self.inner)
    }

    /// The driver's `conductor_idle_strategy_init_args` setting (`aeron_driver_context_get_conductor_idle_strategy_init_args`).
    pub fn conductor_idle_strategy_init_args(&self) -> String {
        ffi::driver_get_conductor_idle_strategy_init_args(&self.inner)
    }

    /// The driver's `connect_enabled` setting (`aeron_driver_context_get_connect_enabled`).
    pub fn connect_enabled(&self) -> i32 {
        ffi::driver_get_connect_enabled(&self.inner)
    }

    /// The driver's `counters_buffer_length` setting (`aeron_driver_context_get_counters_buffer_length`).
    pub fn counters_buffer_length(&self) -> usize {
        ffi::driver_get_counters_buffer_length(&self.inner)
    }

    /// The driver's `counters_free_to_reuse_timeout_ns` setting (`aeron_driver_context_get_counters_free_to_reuse_timeout_ns`).
    pub fn counters_free_to_reuse_timeout_ns(&self) -> u64 {
        ffi::driver_get_counters_free_to_reuse_timeout_ns(&self.inner)
    }

    /// The driver's `cpuset_affinity` setting (`aeron_driver_context_get_cpuset_affinity`).
    pub fn cpuset_affinity(&self) -> bool {
        ffi::driver_get_cpuset_affinity(&self.inner)
    }

    /// The driver's `cpuset_warnings_as_errors` setting (`aeron_driver_context_get_cpuset_warnings_as_errors`).
    pub fn cpuset_warnings_as_errors(&self) -> bool {
        ffi::driver_get_cpuset_warnings_as_errors(&self.inner)
    }

    /// The driver's `dir` setting (`aeron_driver_context_get_dir`).
    pub fn dir(&self) -> String {
        ffi::driver_get_dir(&self.inner)
    }

    /// The driver's `dir_delete_on_shutdown` setting (`aeron_driver_context_get_dir_delete_on_shutdown`).
    pub fn dir_delete_on_shutdown(&self) -> bool {
        ffi::driver_get_dir_delete_on_shutdown(&self.inner)
    }

    /// The driver's `dir_delete_on_start` setting (`aeron_driver_context_get_dir_delete_on_start`).
    pub fn dir_delete_on_start(&self) -> bool {
        ffi::driver_get_dir_delete_on_start(&self.inner)
    }

    /// The driver's `dir_warn_if_exists` setting (`aeron_driver_context_get_dir_warn_if_exists`).
    pub fn dir_warn_if_exists(&self) -> bool {
        ffi::driver_get_dir_warn_if_exists(&self.inner)
    }

    /// The driver's `driver_timeout_ms` setting (`aeron_driver_context_get_driver_timeout_ms`).
    pub fn driver_timeout_ms(&self) -> u64 {
        ffi::driver_get_driver_timeout_ms(&self.inner)
    }

    /// The driver's `enable_experimental_features` setting (`aeron_driver_context_get_enable_experimental_features`).
    pub fn enable_experimental_features(&self) -> i32 {
        ffi::driver_get_enable_experimental_features(&self.inner)
    }

    /// The driver's `error_buffer_length` setting (`aeron_driver_context_get_error_buffer_length`).
    pub fn error_buffer_length(&self) -> usize {
        ffi::driver_get_error_buffer_length(&self.inner)
    }

    /// The driver's `file_page_size` setting (`aeron_driver_context_get_file_page_size`).
    pub fn file_page_size(&self) -> usize {
        ffi::driver_get_file_page_size(&self.inner)
    }

    /// The driver's `flow_control_group_min_size` setting (`aeron_driver_context_get_flow_control_group_min_size`).
    pub fn flow_control_group_min_size(&self) -> i32 {
        ffi::driver_get_flow_control_group_min_size(&self.inner)
    }

    /// The driver's `flow_control_group_tag` setting (`aeron_driver_context_get_flow_control_group_tag`).
    pub fn flow_control_group_tag(&self) -> i64 {
        ffi::driver_get_flow_control_group_tag(&self.inner)
    }

    /// The driver's `flow_control_receiver_timeout_ns` setting (`aeron_driver_context_get_flow_control_receiver_timeout_ns`).
    pub fn flow_control_receiver_timeout_ns(&self) -> u64 {
        ffi::driver_get_flow_control_receiver_timeout_ns(&self.inner)
    }

    /// The driver's `image_liveness_timeout_ns` setting (`aeron_driver_context_get_image_liveness_timeout_ns`).
    pub fn image_liveness_timeout_ns(&self) -> u64 {
        ffi::driver_get_image_liveness_timeout_ns(&self.inner)
    }

    /// The driver's `ipc_mtu_length` setting (`aeron_driver_context_get_ipc_mtu_length`).
    pub fn ipc_mtu_length(&self) -> usize {
        ffi::driver_get_ipc_mtu_length(&self.inner)
    }

    /// The driver's `ipc_publication_term_window_length` setting (`aeron_driver_context_get_ipc_publication_term_window_length`).
    pub fn ipc_publication_term_window_length(&self) -> usize {
        ffi::driver_get_ipc_publication_term_window_length(&self.inner)
    }

    /// The driver's `ipc_term_buffer_length` setting (`aeron_driver_context_get_ipc_term_buffer_length`).
    pub fn ipc_term_buffer_length(&self) -> usize {
        ffi::driver_get_ipc_term_buffer_length(&self.inner)
    }

    /// The driver's `loss_report_buffer_length` setting (`aeron_driver_context_get_loss_report_buffer_length`).
    pub fn loss_report_buffer_length(&self) -> usize {
        ffi::driver_get_loss_report_buffer_length(&self.inner)
    }

    /// The driver's `low_file_store_warning_threshold` setting (`aeron_driver_context_get_low_file_store_warning_threshold`).
    pub fn low_file_store_warning_threshold(&self) -> u64 {
        ffi::driver_get_low_file_store_warning_threshold(&self.inner)
    }

    /// The driver's `max_resend` setting (`aeron_driver_context_get_max_resend`).
    pub fn max_resend(&self) -> u32 {
        ffi::driver_get_max_resend(&self.inner)
    }

    /// The driver's `mtu_length` setting (`aeron_driver_context_get_mtu_length`).
    pub fn mtu_length(&self) -> usize {
        ffi::driver_get_mtu_length(&self.inner)
    }

    /// The driver's `nak_multicast_group_size` setting (`aeron_driver_context_get_nak_multicast_group_size`).
    pub fn nak_multicast_group_size(&self) -> usize {
        ffi::driver_get_nak_multicast_group_size(&self.inner)
    }

    /// The driver's `nak_multicast_max_backoff_ns` setting (`aeron_driver_context_get_nak_multicast_max_backoff_ns`).
    pub fn nak_multicast_max_backoff_ns(&self) -> u64 {
        ffi::driver_get_nak_multicast_max_backoff_ns(&self.inner)
    }

    /// The driver's `nak_unicast_delay_ns` setting (`aeron_driver_context_get_nak_unicast_delay_ns`).
    pub fn nak_unicast_delay_ns(&self) -> u64 {
        ffi::driver_get_nak_unicast_delay_ns(&self.inner)
    }

    /// The driver's `nak_unicast_retry_delay_ratio` setting (`aeron_driver_context_get_nak_unicast_retry_delay_ratio`).
    pub fn nak_unicast_retry_delay_ratio(&self) -> u64 {
        ffi::driver_get_nak_unicast_retry_delay_ratio(&self.inner)
    }

    /// The driver's `name_resolver_init_args` setting (`aeron_driver_context_get_name_resolver_init_args`).
    pub fn name_resolver_init_args(&self) -> String {
        ffi::driver_get_name_resolver_init_args(&self.inner)
    }

    /// The driver's `name_resolver_threshold_ns` setting (`aeron_driver_context_get_name_resolver_threshold_ns`).
    pub fn name_resolver_threshold_ns(&self) -> i64 {
        ffi::driver_get_name_resolver_threshold_ns(&self.inner)
    }

    /// The driver's `native_resource_agent_cpu_affinity` setting (`aeron_driver_context_get_native_resource_agent_cpu_affinity`).
    pub fn native_resource_agent_cpu_affinity(&self) -> i32 {
        ffi::driver_get_native_resource_agent_cpu_affinity(&self.inner)
    }

    /// The driver's `native_resource_agent_idle_strategy` setting (`aeron_driver_context_get_native_resource_agent_idle_strategy`).
    pub fn native_resource_agent_idle_strategy(&self) -> String {
        ffi::driver_get_native_resource_agent_idle_strategy(&self.inner)
    }

    /// The driver's `native_resource_agent_idle_strategy_init_args` setting (`aeron_driver_context_get_native_resource_agent_idle_strategy_init_args`).
    pub fn native_resource_agent_idle_strategy_init_args(&self) -> String {
        ffi::driver_get_native_resource_agent_idle_strategy_init_args(&self.inner)
    }

    /// The driver's `network_publication_max_messages_per_send` setting (`aeron_driver_context_get_network_publication_max_messages_per_send`).
    pub fn network_publication_max_messages_per_send(&self) -> u32 {
        ffi::driver_get_network_publication_max_messages_per_send(&self.inner)
    }

    /// The driver's `perform_storage_checks` setting (`aeron_driver_context_get_perform_storage_checks`).
    pub fn perform_storage_checks(&self) -> bool {
        ffi::driver_get_perform_storage_checks(&self.inner)
    }

    /// The driver's `print_configuration` setting (`aeron_driver_context_get_print_configuration`).
    pub fn print_configuration(&self) -> bool {
        ffi::driver_get_print_configuration(&self.inner)
    }

    /// The driver's `publication_connection_timeout_ns` setting (`aeron_driver_context_get_publication_connection_timeout_ns`).
    pub fn publication_connection_timeout_ns(&self) -> u64 {
        ffi::driver_get_publication_connection_timeout_ns(&self.inner)
    }

    /// The driver's `publication_linger_timeout_ns` setting (`aeron_driver_context_get_publication_linger_timeout_ns`).
    pub fn publication_linger_timeout_ns(&self) -> u64 {
        ffi::driver_get_publication_linger_timeout_ns(&self.inner)
    }

    /// The driver's `publication_reserved_session_id_high` setting (`aeron_driver_context_get_publication_reserved_session_id_high`).
    pub fn publication_reserved_session_id_high(&self) -> i32 {
        ffi::driver_get_publication_reserved_session_id_high(&self.inner)
    }

    /// The driver's `publication_reserved_session_id_low` setting (`aeron_driver_context_get_publication_reserved_session_id_low`).
    pub fn publication_reserved_session_id_low(&self) -> i32 {
        ffi::driver_get_publication_reserved_session_id_low(&self.inner)
    }

    /// The driver's `publication_term_window_length` setting (`aeron_driver_context_get_publication_term_window_length`).
    pub fn publication_term_window_length(&self) -> usize {
        ffi::driver_get_publication_term_window_length(&self.inner)
    }

    /// The driver's `publication_unblock_timeout_ns` setting (`aeron_driver_context_get_publication_unblock_timeout_ns`).
    pub fn publication_unblock_timeout_ns(&self) -> u64 {
        ffi::driver_get_publication_unblock_timeout_ns(&self.inner)
    }

    /// The driver's `rcv_initial_window_length` setting (`aeron_driver_context_get_rcv_initial_window_length`).
    pub fn rcv_initial_window_length(&self) -> usize {
        ffi::driver_get_rcv_initial_window_length(&self.inner)
    }

    /// The driver's `rcv_status_message_timeout_ns` setting (`aeron_driver_context_get_rcv_status_message_timeout_ns`).
    pub fn rcv_status_message_timeout_ns(&self) -> u64 {
        ffi::driver_get_rcv_status_message_timeout_ns(&self.inner)
    }

    /// The driver's `re_resolution_check_interval_ns` setting (`aeron_driver_context_get_re_resolution_check_interval_ns`).
    pub fn re_resolution_check_interval_ns(&self) -> u64 {
        ffi::driver_get_re_resolution_check_interval_ns(&self.inner)
    }

    /// The driver's `receiver_cpu_affinity` setting (`aeron_driver_context_get_receiver_cpu_affinity`).
    pub fn receiver_cpu_affinity(&self) -> i32 {
        ffi::driver_get_receiver_cpu_affinity(&self.inner)
    }

    /// The driver's `receiver_cycle_threshold_ns` setting (`aeron_driver_context_get_receiver_cycle_threshold_ns`).
    pub fn receiver_cycle_threshold_ns(&self) -> i64 {
        ffi::driver_get_receiver_cycle_threshold_ns(&self.inner)
    }

    /// The driver's `receiver_group_consideration` setting (`aeron_driver_context_get_receiver_group_consideration`).
    pub fn receiver_group_consideration(&self) -> InferableBoolean {
        InferableBoolean::from_c(ffi::driver_get_receiver_group_consideration(&self.inner))
    }

    /// The driver's `receiver_group_tag_is_present` setting (`aeron_driver_context_get_receiver_group_tag_is_present`).
    pub fn receiver_group_tag_is_present(&self) -> bool {
        ffi::driver_get_receiver_group_tag_is_present(&self.inner)
    }

    /// The driver's `receiver_group_tag_value` setting (`aeron_driver_context_get_receiver_group_tag_value`).
    pub fn receiver_group_tag_value(&self) -> i64 {
        ffi::driver_get_receiver_group_tag_value(&self.inner)
    }

    /// The driver's `receiver_idle_strategy` setting (`aeron_driver_context_get_receiver_idle_strategy`).
    pub fn receiver_idle_strategy(&self) -> String {
        ffi::driver_get_receiver_idle_strategy(&self.inner)
    }

    /// The driver's `receiver_idle_strategy_init_args` setting (`aeron_driver_context_get_receiver_idle_strategy_init_args`).
    pub fn receiver_idle_strategy_init_args(&self) -> String {
        ffi::driver_get_receiver_idle_strategy_init_args(&self.inner)
    }

    /// The driver's `receiver_io_vector_capacity` setting (`aeron_driver_context_get_receiver_io_vector_capacity`).
    pub fn receiver_io_vector_capacity(&self) -> u32 {
        ffi::driver_get_receiver_io_vector_capacity(&self.inner)
    }

    /// The driver's `rejoin_stream` setting (`aeron_driver_context_get_rejoin_stream`).
    pub fn rejoin_stream(&self) -> bool {
        ffi::driver_get_rejoin_stream(&self.inner)
    }

    /// The driver's `reliable_stream` setting (`aeron_driver_context_get_reliable_stream`).
    pub fn reliable_stream(&self) -> bool {
        ffi::driver_get_reliable_stream(&self.inner)
    }

    /// The driver's `resolver_bootstrap_neighbor` setting (`aeron_driver_context_get_resolver_bootstrap_neighbor`).
    pub fn resolver_bootstrap_neighbor(&self) -> String {
        ffi::driver_get_resolver_bootstrap_neighbor(&self.inner)
    }

    /// The driver's `resolver_bootstrap_resolution_interval_ns` setting (`aeron_driver_context_get_resolver_bootstrap_resolution_interval_ns`).
    pub fn resolver_bootstrap_resolution_interval_ns(&self) -> u64 {
        ffi::driver_get_resolver_bootstrap_resolution_interval_ns(&self.inner)
    }

    /// The driver's `resolver_interface` setting (`aeron_driver_context_get_resolver_interface`).
    pub fn resolver_interface(&self) -> String {
        ffi::driver_get_resolver_interface(&self.inner)
    }

    /// The driver's `resolver_name` setting (`aeron_driver_context_get_resolver_name`).
    pub fn resolver_name(&self) -> String {
        ffi::driver_get_resolver_name(&self.inner)
    }

    /// The driver's `resolver_neighbor_resolution_interval_ns` setting (`aeron_driver_context_get_resolver_neighbor_resolution_interval_ns`).
    pub fn resolver_neighbor_resolution_interval_ns(&self) -> u64 {
        ffi::driver_get_resolver_neighbor_resolution_interval_ns(&self.inner)
    }

    /// The driver's `resolver_neighbor_timeout_ns` setting (`aeron_driver_context_get_resolver_neighbor_timeout_ns`).
    pub fn resolver_neighbor_timeout_ns(&self) -> u64 {
        ffi::driver_get_resolver_neighbor_timeout_ns(&self.inner)
    }

    /// The driver's `resource_free_limit` setting (`aeron_driver_context_get_resource_free_limit`).
    pub fn resource_free_limit(&self) -> u32 {
        ffi::driver_get_resource_free_limit(&self.inner)
    }

    /// The driver's `retransmit_unicast_delay_ns` setting (`aeron_driver_context_get_retransmit_unicast_delay_ns`).
    pub fn retransmit_unicast_delay_ns(&self) -> u64 {
        ffi::driver_get_retransmit_unicast_delay_ns(&self.inner)
    }

    /// The driver's `retransmit_unicast_linger_ns` setting (`aeron_driver_context_get_retransmit_unicast_linger_ns`).
    pub fn retransmit_unicast_linger_ns(&self) -> u64 {
        ffi::driver_get_retransmit_unicast_linger_ns(&self.inner)
    }

    /// The driver's `self_resolution_interval_ns` setting (`aeron_driver_context_get_self_resolution_interval_ns`).
    pub fn self_resolution_interval_ns(&self) -> u64 {
        ffi::driver_get_self_resolution_interval_ns(&self.inner)
    }

    /// The driver's `send_to_status_poll_ratio` setting (`aeron_driver_context_get_send_to_status_poll_ratio`).
    pub fn send_to_status_poll_ratio(&self) -> usize {
        ffi::driver_get_send_to_status_poll_ratio(&self.inner)
    }

    /// The driver's `sender_cpu_affinity` setting (`aeron_driver_context_get_sender_cpu_affinity`).
    pub fn sender_cpu_affinity(&self) -> i32 {
        ffi::driver_get_sender_cpu_affinity(&self.inner)
    }

    /// The driver's `sender_cycle_threshold_ns` setting (`aeron_driver_context_get_sender_cycle_threshold_ns`).
    pub fn sender_cycle_threshold_ns(&self) -> i64 {
        ffi::driver_get_sender_cycle_threshold_ns(&self.inner)
    }

    /// The driver's `sender_idle_strategy` setting (`aeron_driver_context_get_sender_idle_strategy`).
    pub fn sender_idle_strategy(&self) -> String {
        ffi::driver_get_sender_idle_strategy(&self.inner)
    }

    /// The driver's `sender_idle_strategy_init_args` setting (`aeron_driver_context_get_sender_idle_strategy_init_args`).
    pub fn sender_idle_strategy_init_args(&self) -> String {
        ffi::driver_get_sender_idle_strategy_init_args(&self.inner)
    }

    /// The driver's `sender_io_vector_capacity` setting (`aeron_driver_context_get_sender_io_vector_capacity`).
    pub fn sender_io_vector_capacity(&self) -> u32 {
        ffi::driver_get_sender_io_vector_capacity(&self.inner)
    }

    /// The driver's `shared_idle_strategy` setting (`aeron_driver_context_get_shared_idle_strategy`).
    pub fn shared_idle_strategy(&self) -> String {
        ffi::driver_get_shared_idle_strategy(&self.inner)
    }

    /// The driver's `shared_idle_strategy_init_args` setting (`aeron_driver_context_get_shared_idle_strategy_init_args`).
    pub fn shared_idle_strategy_init_args(&self) -> String {
        ffi::driver_get_shared_idle_strategy_init_args(&self.inner)
    }

    /// The driver's `sharednetwork_idle_strategy` setting (`aeron_driver_context_get_sharednetwork_idle_strategy`).
    pub fn sharednetwork_idle_strategy(&self) -> String {
        ffi::driver_get_sharednetwork_idle_strategy(&self.inner)
    }

    /// The driver's `sharednetwork_idle_strategy_init_args` setting (`aeron_driver_context_get_sharednetwork_idle_strategy_init_args`).
    pub fn sharednetwork_idle_strategy_init_args(&self) -> String {
        ffi::driver_get_sharednetwork_idle_strategy_init_args(&self.inner)
    }

    /// The driver's `socket_multicast_ttl` setting (`aeron_driver_context_get_socket_multicast_ttl`).
    pub fn socket_multicast_ttl(&self) -> u8 {
        ffi::driver_get_socket_multicast_ttl(&self.inner)
    }

    /// The driver's `socket_so_rcvbuf` setting (`aeron_driver_context_get_socket_so_rcvbuf`).
    pub fn socket_so_rcvbuf(&self) -> usize {
        ffi::driver_get_socket_so_rcvbuf(&self.inner)
    }

    /// The driver's `socket_so_sndbuf` setting (`aeron_driver_context_get_socket_so_sndbuf`).
    pub fn socket_so_sndbuf(&self) -> usize {
        ffi::driver_get_socket_so_sndbuf(&self.inner)
    }

    /// The driver's `spies_simulate_connection` setting (`aeron_driver_context_get_spies_simulate_connection`).
    pub fn spies_simulate_connection(&self) -> bool {
        ffi::driver_get_spies_simulate_connection(&self.inner)
    }

    /// The driver's `stream_session_limit` setting (`aeron_driver_context_get_stream_session_limit`).
    pub fn stream_session_limit(&self) -> i32 {
        ffi::driver_get_stream_session_limit(&self.inner)
    }

    /// The driver's `term_buffer_length` setting (`aeron_driver_context_get_term_buffer_length`).
    pub fn term_buffer_length(&self) -> usize {
        ffi::driver_get_term_buffer_length(&self.inner)
    }

    /// The driver's `term_buffer_sparse_file` setting (`aeron_driver_context_get_term_buffer_sparse_file`).
    pub fn term_buffer_sparse_file(&self) -> bool {
        ffi::driver_get_term_buffer_sparse_file(&self.inner)
    }

    /// The driver's `tether_subscriptions` setting (`aeron_driver_context_get_tether_subscriptions`).
    pub fn tether_subscriptions(&self) -> bool {
        ffi::driver_get_tether_subscriptions(&self.inner)
    }

    /// The driver's `thread_naming` setting (`aeron_driver_context_get_thread_naming`).
    pub fn thread_naming(&self) -> ThreadNaming {
        ThreadNaming::from_c(ffi::driver_get_thread_naming(&self.inner))
    }

    /// The driver's `timer_interval_ns` setting (`aeron_driver_context_get_timer_interval_ns`).
    pub fn timer_interval_ns(&self) -> u64 {
        ffi::driver_get_timer_interval_ns(&self.inner)
    }

    /// The driver's `to_clients_buffer_length` setting (`aeron_driver_context_get_to_clients_buffer_length`).
    pub fn to_clients_buffer_length(&self) -> usize {
        ffi::driver_get_to_clients_buffer_length(&self.inner)
    }

    /// The driver's `to_conductor_buffer_length` setting (`aeron_driver_context_get_to_conductor_buffer_length`).
    pub fn to_conductor_buffer_length(&self) -> usize {
        ffi::driver_get_to_conductor_buffer_length(&self.inner)
    }

    /// The driver's `untethered_linger_timeout_ns` setting (`aeron_driver_context_get_untethered_linger_timeout_ns`).
    pub fn untethered_linger_timeout_ns(&self) -> i64 {
        ffi::driver_get_untethered_linger_timeout_ns(&self.inner)
    }

    /// The driver's `untethered_resting_timeout_ns` setting (`aeron_driver_context_get_untethered_resting_timeout_ns`).
    pub fn untethered_resting_timeout_ns(&self) -> u64 {
        ffi::driver_get_untethered_resting_timeout_ns(&self.inner)
    }

    /// The driver's `untethered_window_limit_timeout_ns` setting (`aeron_driver_context_get_untethered_window_limit_timeout_ns`).
    pub fn untethered_window_limit_timeout_ns(&self) -> u64 {
        ffi::driver_get_untethered_window_limit_timeout_ns(&self.inner)
    }
}
