// @generated by scripts/gen_driver_context.py from aeron-driver/src/main/c/aeronmd.h (aeron-1.53.3). Do not edit.
#pragma once
#include "shim.h"

extern "C" {
#include <aeronmd.h>
}

namespace aeron_rs {

inline rust::String lossyOrEmpty(const char *value) {
    return rust::String::lossy(value == nullptr ? "" : value);
}

inline void driver_set_dir(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_dir(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set dir");
    }
}

inline void driver_set_dir_warn_if_exists(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_dir_warn_if_exists(driver.context(), value) < 0) {
        throwDriverError("Failed to set dir_warn_if_exists");
    }
}

inline void driver_set_thread_naming(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_thread_naming(driver.context(), static_cast<aeron_thread_naming_t>(value)) < 0) {
        throwDriverError("Failed to set thread_naming");
    }
}

inline void driver_set_dir_delete_on_start(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_dir_delete_on_start(driver.context(), value) < 0) {
        throwDriverError("Failed to set dir_delete_on_start");
    }
}

inline void driver_set_dir_delete_on_shutdown(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_dir_delete_on_shutdown(driver.context(), value) < 0) {
        throwDriverError("Failed to set dir_delete_on_shutdown");
    }
}

inline void driver_set_to_conductor_buffer_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_to_conductor_buffer_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set to_conductor_buffer_length");
    }
}

inline void driver_set_to_clients_buffer_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_to_clients_buffer_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set to_clients_buffer_length");
    }
}

inline void driver_set_counters_buffer_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_counters_buffer_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set counters_buffer_length");
    }
}

inline void driver_set_error_buffer_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_error_buffer_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set error_buffer_length");
    }
}

inline void driver_set_client_liveness_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_client_liveness_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set client_liveness_timeout_ns");
    }
}

inline void driver_set_term_buffer_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_term_buffer_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set term_buffer_length");
    }
}

inline void driver_set_ipc_term_buffer_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_ipc_term_buffer_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set ipc_term_buffer_length");
    }
}

inline void driver_set_term_buffer_sparse_file(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_term_buffer_sparse_file(driver.context(), value) < 0) {
        throwDriverError("Failed to set term_buffer_sparse_file");
    }
}

inline void driver_set_perform_storage_checks(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_perform_storage_checks(driver.context(), value) < 0) {
        throwDriverError("Failed to set perform_storage_checks");
    }
}

inline void driver_set_low_file_store_warning_threshold(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_low_file_store_warning_threshold(driver.context(), value) < 0) {
        throwDriverError("Failed to set low_file_store_warning_threshold");
    }
}

inline void driver_set_spies_simulate_connection(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_spies_simulate_connection(driver.context(), value) < 0) {
        throwDriverError("Failed to set spies_simulate_connection");
    }
}

inline void driver_set_file_page_size(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_file_page_size(driver.context(), value) < 0) {
        throwDriverError("Failed to set file_page_size");
    }
}

inline void driver_set_mtu_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_mtu_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set mtu_length");
    }
}

inline void driver_set_ipc_mtu_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_ipc_mtu_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set ipc_mtu_length");
    }
}

inline void driver_set_ipc_publication_term_window_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_ipc_publication_term_window_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set ipc_publication_term_window_length");
    }
}

inline void driver_set_publication_term_window_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_publication_term_window_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set publication_term_window_length");
    }
}

inline void driver_set_publication_linger_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_publication_linger_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set publication_linger_timeout_ns");
    }
}

inline void driver_set_socket_so_rcvbuf(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_socket_so_rcvbuf(driver.context(), value) < 0) {
        throwDriverError("Failed to set socket_so_rcvbuf");
    }
}

inline void driver_set_socket_so_sndbuf(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_socket_so_sndbuf(driver.context(), value) < 0) {
        throwDriverError("Failed to set socket_so_sndbuf");
    }
}

inline void driver_set_socket_multicast_ttl(MediaDriverWrapper &driver, uint8_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_socket_multicast_ttl(driver.context(), value) < 0) {
        throwDriverError("Failed to set socket_multicast_ttl");
    }
}

inline void driver_set_send_to_status_poll_ratio(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_send_to_status_poll_ratio(driver.context(), value) < 0) {
        throwDriverError("Failed to set send_to_status_poll_ratio");
    }
}

inline void driver_set_rcv_status_message_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_rcv_status_message_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set rcv_status_message_timeout_ns");
    }
}

inline void driver_set_image_liveness_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_image_liveness_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set image_liveness_timeout_ns");
    }
}

inline void driver_set_rcv_initial_window_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_rcv_initial_window_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set rcv_initial_window_length");
    }
}

inline void driver_set_loss_report_buffer_length(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_loss_report_buffer_length(driver.context(), value) < 0) {
        throwDriverError("Failed to set loss_report_buffer_length");
    }
}

inline void driver_set_publication_unblock_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_publication_unblock_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set publication_unblock_timeout_ns");
    }
}

inline void driver_set_publication_connection_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_publication_connection_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set publication_connection_timeout_ns");
    }
}

inline void driver_set_timer_interval_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_timer_interval_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set timer_interval_ns");
    }
}

inline void driver_set_sender_idle_strategy(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sender_idle_strategy(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set sender_idle_strategy");
    }
}

inline void driver_set_conductor_idle_strategy(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_conductor_idle_strategy(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set conductor_idle_strategy");
    }
}

inline void driver_set_receiver_idle_strategy(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_idle_strategy(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set receiver_idle_strategy");
    }
}

inline void driver_set_sharednetwork_idle_strategy(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sharednetwork_idle_strategy(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set sharednetwork_idle_strategy");
    }
}

inline void driver_set_shared_idle_strategy(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_shared_idle_strategy(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set shared_idle_strategy");
    }
}

inline void driver_set_sender_idle_strategy_init_args(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sender_idle_strategy_init_args(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set sender_idle_strategy_init_args");
    }
}

inline void driver_set_conductor_idle_strategy_init_args(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_conductor_idle_strategy_init_args(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set conductor_idle_strategy_init_args");
    }
}

inline void driver_set_receiver_idle_strategy_init_args(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_idle_strategy_init_args(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set receiver_idle_strategy_init_args");
    }
}

inline void driver_set_sharednetwork_idle_strategy_init_args(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sharednetwork_idle_strategy_init_args(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set sharednetwork_idle_strategy_init_args");
    }
}

inline void driver_set_shared_idle_strategy_init_args(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_shared_idle_strategy_init_args(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set shared_idle_strategy_init_args");
    }
}

inline void driver_set_native_resource_agent_idle_strategy(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_native_resource_agent_idle_strategy(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set native_resource_agent_idle_strategy");
    }
}

inline void driver_set_native_resource_agent_idle_strategy_init_args(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_native_resource_agent_idle_strategy_init_args(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set native_resource_agent_idle_strategy_init_args");
    }
}

inline void driver_set_counters_free_to_reuse_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_counters_free_to_reuse_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set counters_free_to_reuse_timeout_ns");
    }
}

inline void driver_set_flow_control_receiver_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_flow_control_receiver_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set flow_control_receiver_timeout_ns");
    }
}

inline void driver_set_flow_control_group_tag(MediaDriverWrapper &driver, int64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_flow_control_group_tag(driver.context(), value) < 0) {
        throwDriverError("Failed to set flow_control_group_tag");
    }
}

inline void driver_set_flow_control_group_min_size(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_flow_control_group_min_size(driver.context(), value) < 0) {
        throwDriverError("Failed to set flow_control_group_min_size");
    }
}

inline void driver_set_receiver_group_tag(MediaDriverWrapper &driver, bool is_present, int64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_group_tag(driver.context(), is_present, value) < 0) {
        throwDriverError("Failed to set receiver_group_tag");
    }
}

inline void driver_set_print_configuration(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_print_configuration(driver.context(), value) < 0) {
        throwDriverError("Failed to set print_configuration");
    }
}

inline void driver_set_reliable_stream(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_reliable_stream(driver.context(), value) < 0) {
        throwDriverError("Failed to set reliable_stream");
    }
}

inline void driver_set_tether_subscriptions(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_tether_subscriptions(driver.context(), value) < 0) {
        throwDriverError("Failed to set tether_subscriptions");
    }
}

inline void driver_set_untethered_window_limit_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_untethered_window_limit_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set untethered_window_limit_timeout_ns");
    }
}

inline void driver_set_untethered_linger_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_untethered_linger_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set untethered_linger_timeout_ns");
    }
}

inline void driver_set_untethered_resting_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_untethered_resting_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set untethered_resting_timeout_ns");
    }
}

inline void driver_set_driver_timeout_ms(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_driver_timeout_ms(driver.context(), value) < 0) {
        throwDriverError("Failed to set driver_timeout_ms");
    }
}

inline void driver_set_nak_multicast_group_size(MediaDriverWrapper &driver, size_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_nak_multicast_group_size(driver.context(), value) < 0) {
        throwDriverError("Failed to set nak_multicast_group_size");
    }
}

inline void driver_set_nak_multicast_max_backoff_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_nak_multicast_max_backoff_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set nak_multicast_max_backoff_ns");
    }
}

inline void driver_set_nak_unicast_delay_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_nak_unicast_delay_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set nak_unicast_delay_ns");
    }
}

inline void driver_set_nak_unicast_retry_delay_ratio(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_nak_unicast_retry_delay_ratio(driver.context(), value) < 0) {
        throwDriverError("Failed to set nak_unicast_retry_delay_ratio");
    }
}

inline void driver_set_max_resend(MediaDriverWrapper &driver, uint32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_max_resend(driver.context(), value) < 0) {
        throwDriverError("Failed to set max_resend");
    }
}

inline void driver_set_retransmit_unicast_delay_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_retransmit_unicast_delay_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set retransmit_unicast_delay_ns");
    }
}

inline void driver_set_retransmit_unicast_linger_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_retransmit_unicast_linger_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set retransmit_unicast_linger_ns");
    }
}

inline void driver_set_receiver_group_consideration(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_group_consideration(driver.context(), static_cast<aeron_inferable_boolean_t>(value)) < 0) {
        throwDriverError("Failed to set receiver_group_consideration");
    }
}

inline void driver_set_rejoin_stream(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_rejoin_stream(driver.context(), value) < 0) {
        throwDriverError("Failed to set rejoin_stream");
    }
}

inline void driver_set_connect_enabled(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_connect_enabled(driver.context(), value) < 0) {
        throwDriverError("Failed to set connect_enabled");
    }
}

inline void driver_set_publication_reserved_session_id_low(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_publication_reserved_session_id_low(driver.context(), value) < 0) {
        throwDriverError("Failed to set publication_reserved_session_id_low");
    }
}

inline void driver_set_publication_reserved_session_id_high(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_publication_reserved_session_id_high(driver.context(), value) < 0) {
        throwDriverError("Failed to set publication_reserved_session_id_high");
    }
}

inline void driver_set_resolver_name(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_resolver_name(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set resolver_name");
    }
}

inline void driver_set_resolver_interface(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_resolver_interface(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set resolver_interface");
    }
}

inline void driver_set_resolver_bootstrap_neighbor(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_resolver_bootstrap_neighbor(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set resolver_bootstrap_neighbor");
    }
}

inline void driver_set_name_resolver_init_args(MediaDriverWrapper &driver, rust::Str value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_name_resolver_init_args(driver.context(), std::string(value.data(), value.size()).c_str()) < 0) {
        throwDriverError("Failed to set name_resolver_init_args");
    }
}

inline void driver_set_resolver_neighbor_timeout_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_resolver_neighbor_timeout_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set resolver_neighbor_timeout_ns");
    }
}

inline void driver_set_self_resolution_interval_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_self_resolution_interval_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set self_resolution_interval_ns");
    }
}

inline void driver_set_resolver_neighbor_resolution_interval_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_resolver_neighbor_resolution_interval_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set resolver_neighbor_resolution_interval_ns");
    }
}

inline void driver_set_resolver_bootstrap_neighbor_resolution_interval_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_resolver_bootstrap_neighbor_resolution_interval_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set resolver_bootstrap_neighbor_resolution_interval_ns");
    }
}

inline void driver_set_re_resolution_check_interval_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_re_resolution_check_interval_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set re_resolution_check_interval_ns");
    }
}

inline void driver_set_sender_wildcard_port_range(MediaDriverWrapper &driver, uint16_t low, uint16_t high) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sender_wildcard_port_range(driver.context(), low, high) < 0) {
        throwDriverError("Failed to set sender_wildcard_port_range");
    }
}

inline void driver_set_receiver_wildcard_port_range(MediaDriverWrapper &driver, uint16_t low, uint16_t high) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_wildcard_port_range(driver.context(), low, high) < 0) {
        throwDriverError("Failed to set receiver_wildcard_port_range");
    }
}

inline void driver_set_conductor_cycle_threshold_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_conductor_cycle_threshold_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set conductor_cycle_threshold_ns");
    }
}

inline void driver_set_sender_cycle_threshold_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sender_cycle_threshold_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set sender_cycle_threshold_ns");
    }
}

inline void driver_set_receiver_cycle_threshold_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_cycle_threshold_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set receiver_cycle_threshold_ns");
    }
}

inline void driver_set_name_resolver_threshold_ns(MediaDriverWrapper &driver, uint64_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_name_resolver_threshold_ns(driver.context(), value) < 0) {
        throwDriverError("Failed to set name_resolver_threshold_ns");
    }
}

inline void driver_set_receiver_io_vector_capacity(MediaDriverWrapper &driver, uint32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_io_vector_capacity(driver.context(), value) < 0) {
        throwDriverError("Failed to set receiver_io_vector_capacity");
    }
}

inline void driver_set_sender_io_vector_capacity(MediaDriverWrapper &driver, uint32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sender_io_vector_capacity(driver.context(), value) < 0) {
        throwDriverError("Failed to set sender_io_vector_capacity");
    }
}

inline void driver_set_network_publication_max_messages_per_send(MediaDriverWrapper &driver, uint32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_network_publication_max_messages_per_send(driver.context(), value) < 0) {
        throwDriverError("Failed to set network_publication_max_messages_per_send");
    }
}

inline void driver_set_resource_free_limit(MediaDriverWrapper &driver, uint32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_resource_free_limit(driver.context(), value) < 0) {
        throwDriverError("Failed to set resource_free_limit");
    }
}

inline void driver_set_conductor_cpu_affinity(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_conductor_cpu_affinity(driver.context(), value) < 0) {
        throwDriverError("Failed to set conductor_cpu_affinity");
    }
}

inline void driver_set_receiver_cpu_affinity(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_receiver_cpu_affinity(driver.context(), value) < 0) {
        throwDriverError("Failed to set receiver_cpu_affinity");
    }
}

inline void driver_set_sender_cpu_affinity(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_sender_cpu_affinity(driver.context(), value) < 0) {
        throwDriverError("Failed to set sender_cpu_affinity");
    }
}

inline void driver_set_native_resource_agent_cpu_affinity(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_native_resource_agent_cpu_affinity(driver.context(), value) < 0) {
        throwDriverError("Failed to set native_resource_agent_cpu_affinity");
    }
}

inline void driver_set_cpuset_affinity(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_cpuset_affinity(driver.context(), value) < 0) {
        throwDriverError("Failed to set cpuset_affinity");
    }
}

inline void driver_set_cpuset_warnings_as_errors(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_cpuset_warnings_as_errors(driver.context(), value) < 0) {
        throwDriverError("Failed to set cpuset_warnings_as_errors");
    }
}

inline void driver_set_enable_experimental_features(MediaDriverWrapper &driver, bool value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_enable_experimental_features(driver.context(), value) < 0) {
        throwDriverError("Failed to set enable_experimental_features");
    }
}

inline void driver_set_stream_session_limit(MediaDriverWrapper &driver, int32_t value) {
    driver.ensureNotStarted();
    if (aeron_driver_context_set_stream_session_limit(driver.context(), value) < 0) {
        throwDriverError("Failed to set stream_session_limit");
    }
}

inline uint64_t driver_get_client_liveness_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_client_liveness_timeout_ns(driver.context());
}

inline int32_t driver_get_conductor_cpu_affinity(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_conductor_cpu_affinity(driver.context());
}

inline int64_t driver_get_conductor_cycle_threshold_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_conductor_cycle_threshold_ns(driver.context());
}

inline rust::String driver_get_conductor_idle_strategy(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_conductor_idle_strategy(driver.context()));
}

inline rust::String driver_get_conductor_idle_strategy_init_args(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_conductor_idle_strategy_init_args(driver.context()));
}

inline int32_t driver_get_connect_enabled(const MediaDriverWrapper &driver) {
    return static_cast<int32_t>(aeron_driver_context_get_connect_enabled(driver.context()));
}

inline size_t driver_get_counters_buffer_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_counters_buffer_length(driver.context());
}

inline uint64_t driver_get_counters_free_to_reuse_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_counters_free_to_reuse_timeout_ns(driver.context());
}

inline bool driver_get_cpuset_affinity(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_cpuset_affinity(driver.context());
}

inline bool driver_get_cpuset_warnings_as_errors(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_cpuset_warnings_as_errors(driver.context());
}

inline rust::String driver_get_dir(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_dir(driver.context()));
}

inline bool driver_get_dir_delete_on_shutdown(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_dir_delete_on_shutdown(driver.context());
}

inline bool driver_get_dir_delete_on_start(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_dir_delete_on_start(driver.context());
}

inline bool driver_get_dir_warn_if_exists(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_dir_warn_if_exists(driver.context());
}

inline uint64_t driver_get_driver_timeout_ms(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_driver_timeout_ms(driver.context());
}

inline int32_t driver_get_enable_experimental_features(const MediaDriverWrapper &driver) {
    return static_cast<int32_t>(aeron_driver_context_get_enable_experimental_features(driver.context()));
}

inline size_t driver_get_error_buffer_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_error_buffer_length(driver.context());
}

inline size_t driver_get_file_page_size(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_file_page_size(driver.context());
}

inline int32_t driver_get_flow_control_group_min_size(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_flow_control_group_min_size(driver.context());
}

inline int64_t driver_get_flow_control_group_tag(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_flow_control_group_tag(driver.context());
}

inline uint64_t driver_get_flow_control_receiver_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_flow_control_receiver_timeout_ns(driver.context());
}

inline uint64_t driver_get_image_liveness_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_image_liveness_timeout_ns(driver.context());
}

inline size_t driver_get_ipc_mtu_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_ipc_mtu_length(driver.context());
}

inline size_t driver_get_ipc_publication_term_window_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_ipc_publication_term_window_length(driver.context());
}

inline size_t driver_get_ipc_term_buffer_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_ipc_term_buffer_length(driver.context());
}

inline size_t driver_get_loss_report_buffer_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_loss_report_buffer_length(driver.context());
}

inline uint64_t driver_get_low_file_store_warning_threshold(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_low_file_store_warning_threshold(driver.context());
}

inline uint32_t driver_get_max_resend(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_max_resend(driver.context());
}

inline size_t driver_get_mtu_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_mtu_length(driver.context());
}

inline size_t driver_get_nak_multicast_group_size(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_nak_multicast_group_size(driver.context());
}

inline uint64_t driver_get_nak_multicast_max_backoff_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_nak_multicast_max_backoff_ns(driver.context());
}

inline uint64_t driver_get_nak_unicast_delay_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_nak_unicast_delay_ns(driver.context());
}

inline uint64_t driver_get_nak_unicast_retry_delay_ratio(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_nak_unicast_retry_delay_ratio(driver.context());
}

inline rust::String driver_get_name_resolver_init_args(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_name_resolver_init_args(driver.context()));
}

inline int64_t driver_get_name_resolver_threshold_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_name_resolver_threshold_ns(driver.context());
}

inline int32_t driver_get_native_resource_agent_cpu_affinity(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_native_resource_agent_cpu_affinity(driver.context());
}

inline rust::String driver_get_native_resource_agent_idle_strategy(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_native_resource_agent_idle_strategy(driver.context()));
}

inline rust::String driver_get_native_resource_agent_idle_strategy_init_args(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_native_resource_agent_idle_strategy_init_args(driver.context()));
}

inline uint32_t driver_get_network_publication_max_messages_per_send(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_network_publication_max_messages_per_send(driver.context());
}

inline bool driver_get_perform_storage_checks(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_perform_storage_checks(driver.context());
}

inline bool driver_get_print_configuration(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_print_configuration(driver.context());
}

inline uint64_t driver_get_publication_connection_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_publication_connection_timeout_ns(driver.context());
}

inline uint64_t driver_get_publication_linger_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_publication_linger_timeout_ns(driver.context());
}

inline int32_t driver_get_publication_reserved_session_id_high(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_publication_reserved_session_id_high(driver.context());
}

inline int32_t driver_get_publication_reserved_session_id_low(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_publication_reserved_session_id_low(driver.context());
}

inline size_t driver_get_publication_term_window_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_publication_term_window_length(driver.context());
}

inline uint64_t driver_get_publication_unblock_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_publication_unblock_timeout_ns(driver.context());
}

inline size_t driver_get_rcv_initial_window_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_rcv_initial_window_length(driver.context());
}

inline uint64_t driver_get_rcv_status_message_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_rcv_status_message_timeout_ns(driver.context());
}

inline uint64_t driver_get_re_resolution_check_interval_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_re_resolution_check_interval_ns(driver.context());
}

inline int32_t driver_get_receiver_cpu_affinity(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_receiver_cpu_affinity(driver.context());
}

inline int64_t driver_get_receiver_cycle_threshold_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_receiver_cycle_threshold_ns(driver.context());
}

inline int32_t driver_get_receiver_group_consideration(const MediaDriverWrapper &driver) {
    return static_cast<int32_t>(aeron_driver_context_get_receiver_group_consideration(driver.context()));
}

inline bool driver_get_receiver_group_tag_is_present(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_receiver_group_tag_is_present(driver.context());
}

inline int64_t driver_get_receiver_group_tag_value(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_receiver_group_tag_value(driver.context());
}

inline rust::String driver_get_receiver_idle_strategy(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_receiver_idle_strategy(driver.context()));
}

inline rust::String driver_get_receiver_idle_strategy_init_args(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_receiver_idle_strategy_init_args(driver.context()));
}

inline uint32_t driver_get_receiver_io_vector_capacity(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_receiver_io_vector_capacity(driver.context());
}

inline bool driver_get_rejoin_stream(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_rejoin_stream(driver.context());
}

inline bool driver_get_reliable_stream(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_reliable_stream(driver.context());
}

inline rust::String driver_get_resolver_bootstrap_neighbor(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_resolver_bootstrap_neighbor(driver.context()));
}

inline uint64_t driver_get_resolver_bootstrap_resolution_interval_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_resolver_bootstrap_resolution_interval_ns(driver.context());
}

inline rust::String driver_get_resolver_interface(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_resolver_interface(driver.context()));
}

inline rust::String driver_get_resolver_name(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_resolver_name(driver.context()));
}

inline uint64_t driver_get_resolver_neighbor_resolution_interval_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_resolver_neighbor_resolution_interval_ns(driver.context());
}

inline uint64_t driver_get_resolver_neighbor_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_resolver_neighbor_timeout_ns(driver.context());
}

inline uint32_t driver_get_resource_free_limit(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_resource_free_limit(driver.context());
}

inline uint64_t driver_get_retransmit_unicast_delay_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_retransmit_unicast_delay_ns(driver.context());
}

inline uint64_t driver_get_retransmit_unicast_linger_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_retransmit_unicast_linger_ns(driver.context());
}

inline uint64_t driver_get_self_resolution_interval_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_self_resolution_interval_ns(driver.context());
}

inline size_t driver_get_send_to_status_poll_ratio(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_send_to_status_poll_ratio(driver.context());
}

inline int32_t driver_get_sender_cpu_affinity(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_sender_cpu_affinity(driver.context());
}

inline int64_t driver_get_sender_cycle_threshold_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_sender_cycle_threshold_ns(driver.context());
}

inline rust::String driver_get_sender_idle_strategy(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_sender_idle_strategy(driver.context()));
}

inline rust::String driver_get_sender_idle_strategy_init_args(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_sender_idle_strategy_init_args(driver.context()));
}

inline uint32_t driver_get_sender_io_vector_capacity(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_sender_io_vector_capacity(driver.context());
}

inline rust::String driver_get_shared_idle_strategy(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_shared_idle_strategy(driver.context()));
}

inline rust::String driver_get_shared_idle_strategy_init_args(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_shared_idle_strategy_init_args(driver.context()));
}

inline rust::String driver_get_sharednetwork_idle_strategy(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_sharednetwork_idle_strategy(driver.context()));
}

inline rust::String driver_get_sharednetwork_idle_strategy_init_args(const MediaDriverWrapper &driver) {
    return lossyOrEmpty(aeron_driver_context_get_sharednetwork_idle_strategy_init_args(driver.context()));
}

inline uint8_t driver_get_socket_multicast_ttl(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_socket_multicast_ttl(driver.context());
}

inline size_t driver_get_socket_so_rcvbuf(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_socket_so_rcvbuf(driver.context());
}

inline size_t driver_get_socket_so_sndbuf(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_socket_so_sndbuf(driver.context());
}

inline bool driver_get_spies_simulate_connection(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_spies_simulate_connection(driver.context());
}

inline int32_t driver_get_stream_session_limit(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_stream_session_limit(driver.context());
}

inline size_t driver_get_term_buffer_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_term_buffer_length(driver.context());
}

inline bool driver_get_term_buffer_sparse_file(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_term_buffer_sparse_file(driver.context());
}

inline bool driver_get_tether_subscriptions(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_tether_subscriptions(driver.context());
}

inline int32_t driver_get_thread_naming(const MediaDriverWrapper &driver) {
    return static_cast<int32_t>(aeron_driver_context_get_thread_naming(driver.context()));
}

inline uint64_t driver_get_timer_interval_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_timer_interval_ns(driver.context());
}

inline size_t driver_get_to_clients_buffer_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_to_clients_buffer_length(driver.context());
}

inline size_t driver_get_to_conductor_buffer_length(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_to_conductor_buffer_length(driver.context());
}

inline int64_t driver_get_untethered_linger_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_untethered_linger_timeout_ns(driver.context());
}

inline uint64_t driver_get_untethered_resting_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_untethered_resting_timeout_ns(driver.context());
}

inline uint64_t driver_get_untethered_window_limit_timeout_ns(const MediaDriverWrapper &driver) {
    return aeron_driver_context_get_untethered_window_limit_timeout_ns(driver.context());
}

} // namespace aeron_rs
